### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZHENGLOC** [GlodBlock/ExtendedAE#1]
切换资源包或更改语言会导致崩溃

游戏版本：1.19.2
Forge版本：43.2.21
Mod版本：0.0.2

[crash-2023-07-24_21.19.47-client.txt](https://github.com/GlodBlock/ExPatternProvider/files/12146339/crash-2023-07-24_21.19.47-client.txt)

**Comment by GlodBlock** [comment]
0.0.3已修复https://legacy.curseforge.com/minecraft/mc-mods/ex-pattern-provider/files/4662894
