### ISSUE TITLE
[Bug?] Applied Flux Pattern Providers Taking Energy

### ISSUE THREAD

**Issue by Arcanical** [GlodBlock/ExtendedAE#101]
The applied flux source and issue link just go here, so sorry if this isn't the right place.

I'm playing ATM9, standard but for that I added Applied Flux, and after adding the mod, my pattern providers are sucking up energy and now, are so filled with energy they can't accept return items.

This can be seen here:
![image](https://github.com/GlodBlock/ExtendedAE/assets/63728955/e31efc20-b401-486a-b69f-63cc272cfc5a)

Even crazier is that in this case, it's ripping the energy right out of a dissolution chamber from industrial foregoing, which shouldn't be able to give away its energy at all AFAIK.
![image](https://github.com/GlodBlock/ExtendedAE/assets/63728955/962c71df-cbc0-418b-877f-6aee791ba56a)

I'm _fairly_ certain that this is a bug, and quite a big one too. I don't see why this wouldn't be replicable, and I'm using `AppliedFlux-1.20-1.1.3-forge.jar` and `Glodium-1.20-1.3-forge.jar`. AE2 is `appliedenergistics2-forge-15.0.21.jar`.

**Comment by GlodBlock** [comment]
i will investigate it soon

**Comment by Arcanical** [comment]
After getting on this morning and looking things over (trying to work around this), I have learned that pipez (the universal cable is what I used, not sure about energy but most likely) will suck energy out of machines and attempt to dump into pattern providers and interfaces. This fills them up unless a cell can absorb it in the system (I have one, but it's full), stopping any returns or in the case of interfaces, exports from happening.

They won't rip it out of machines on their own, seems like they need it to be pushed into them. Finally, they will drain as the system exports energy places, meaning that if you export more energy overall than gets pumped into them (all of them), this issue might not be noticeable.

Hopefully this information is helpful, thanks for looking into it. Cheers!

**Comment by GlodBlock** [comment]
oh, so it is the universal cable from pipez drained the energy. replacing it with regular item/fluid pipe should fix your issue here. but i can't *fix* it at applied flux side, because it isn't a bug but a wrong setup. it is intended that applied flux allows pattern provider and interface to accept energy.
