### ISSUE TITLE
添加扩展me io端口

### ISSUE THREAD

**Issue by gjmhmm8** [GlodBlock/ExtendedAE#105]
添加扩展me io端口,现在的太慢了

**Comment by gjmhmm8** [comment]
那个改名的你加的还是啥，为啥原版ae我试着没用

**Comment by gjmhmm8** [comment]
<img width="1238" alt="Snipaste_2024-03-22_04-06-11" src="https://github.com/GlodBlock/ExtendedAE/assets/73775469/2acc1a4f-6145-4e7c-b980-02bbd3300680">
官方文档也没说能改名啊

**Comment by gjmhmm8** [comment]
铁砧能改但是贼麻烦

**Comment by GlodBlock** [comment]
我加的石英切割刀右键改名，原版ae没有

**Comment by gjmhmm8** [comment]
建议添加扩展me io端口，最快速率 1tick 多个类型（目前实现有点问题，配合多类型的盘会贼卡，建议单次获取内容，而不是一直重复获取内容，直到无法取出再次获取磁盘内容）

**Comment by GlodBlock** [comment]
加了
