### ISSUE TITLE
[Suggestion] Add overflow destruction card functionality to the infinite cells

### ISSUE THREAD

**Issue by Kevin-Marsh** [GlodBlock/ExtendedAE#107]
I would suggest adding overflow destruction card capabilities to the infinite cells. Right now this will clog if you use them and then cancel a craft or get water or cobble in an interface. I always tell players to place overflow destruction cards into them but it would be better if this functionality was baked into the cells so that new players don't have the issue.

**Comment by GlodBlock** [comment]
added now
