### ISSUE TITLE
P2P connections are not shown with Network Analyzer

### ISSUE THREAD

**Issue by andriihorpenko** [GlodBlock/ExtendedAE#108]
## Description
P2P connections are not showing up in any available mode of the Network Analyzer.
I did some debugging, seems like the Tunnel is not an in world node, hence, `wrapGridNode` returns null.
https://github.com/GlodBlock/ExtendedAE/blob/f5b077fc8be985cef4031c23164b213aff3598ac/src/main/java/com/glodblock/github/ae2netanalyser/common/items/ItemNetworkAnalyser.java#L234
This, in turn, makes this statement return false.
https://github.com/GlodBlock/ExtendedAE/blob/f5b077fc8be985cef4031c23164b213aff3598ac/src/main/java/com/glodblock/github/ae2netanalyser/common/items/ItemNetworkAnalyser.java#L195

## Screenshot
Full mode selected, P2P connection established via Memory Card
<img width="1728" alt="Screenshot 2024-03-26 at 03 16 32" src="https://github.com/GlodBlock/ExtendedAE/assets/13716167/fb101ebf-ebf1-4c6c-8a45-94983b92e07a">

**Comment by andriihorpenko** [comment]
If I get it right, this feature works only with ME P2P Tunnel according to the guide. Isn't it possible to support other Tunnel types?

**Comment by GlodBlock** [comment]
it is desgined for me p2p only for now. i am working on another tool for all types p2p display https://github.com/GlodBlock/ExtendedAE/tree/analyser/p2p-wip

**Comment by andriihorpenko** [comment]
That is great! Thanks for a quick answer.
