### ISSUE TITLE
Possibility of 1.18.2 support?

### ISSUE THREAD

**Issue by rumpled** [GlodBlock/ExtendedAE#109]
I don't see it documented anywhere here, but the mod page at https://www.curseforge.com/minecraft/mc-mods/ae2-network-analyser points to this repo. Tested it out and it's definitely included.

I'm looking for an AE2 network visualization tool and this seems to be the only one that's still maintained.

Unfortunately I'm on 1.18.2 instead of 1.20.1 so I just miss the bar. Any chance it could be backported?

If not, where would you guesstimate the difficulty of pulling out just the Network Analyzer to port for someone who's never written a mod before? :)  I wouldn't mind taking a stab at it.

**Comment by GlodBlock** [comment]
sadly no, i don't have much energy to maintance mods at multiple versions at the same time. feel free to backport it, here is the source code https://github.com/GlodBlock/ExtendedAE/tree/analyser/1.20.1-forge
