### ISSUE TITLE
[Feature Request] Add Neeve's AE2: Extended Life Additions into your mod

### ISSUE THREAD

**Issue by Leclowndu93150** [GlodBlock/ExtendedAE#11]
Hello, it would be really nice if you could port that feature
thank you for your mod btw

**Comment by GlodBlock** [comment]
added in 0.1.13 https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-0.1.13-forge

**Comment by Leclowndu93150** [comment]
insane
