### ISSUE TITLE
Placing a Gregtech tool inside the AE2 smithing table encoding terminal causes crash

### ISSUE THREAD

**Issue by williamrzhou** [GlodBlock/ExtendedAE#113]
Playing on ATM9 v0.2.54, ExtendedAE v1.20-1.0.16-forge

Moved a Gregtech tool (specifically diamond wrench) into AE2 pattern encoding terminal (wireless) while the terminal was accidentally set to smithing table recipe encoding mode. Immediate crash upon doing so, and unable to remove the item from the encoding terminal since the UI cannot be opened without crashing. Had to fix by trashing the wireless terminal and creating a new one.

Crash Log
https://gist.github.com/eziur/b5f5722af96dfe2ac4bf79373a1c88b5

Latest.Log
https://gist.github.com/eziur/a925947b17fb5922f2f750dc33d40371

**Comment by GlodBlock** [comment]
fixed by https://github.com/GlodBlock/ExtendedAE/commit/fb49c3e26cadbc4e0ff6f380b595b0e725b7992c
