### ISSUE TITLE
Long energy transfers

### ISSUE THREAD

**Issue by ArthwrWilly** [GlodBlock/ExtendedAE#114]
Ability for the Applied Flux to see and transfer values greater than the 32bit integer limit.
Like Flux Networks and Mekanism can do.
![2024-03-29_09 11 14](https://github.com/GlodBlock/ExtendedAE/assets/30034331/a5b782e3-0a98-4681-a885-cb626b4b61f0)

**Comment by GlodBlock** [comment]
latest is supported
