### ISSUE TITLE
Extended pattern provider does not show name when placed as cable subpart

### ISSUE THREAD

**Issue by williamrzhou** [GlodBlock/ExtendedAE#115]
Rename extended pattern with anvil while it is in flat form (cable subpart), place down. Jade/JEI UI does not show pattern provider name, opening pattern provider with right click also does not show name, and if broken or wrenched after placing, the item does not show new name in inventory. In pattern access terminal the name will show, but it becomes hard to keep track of pattern providers.

**Comment by GlodBlock** [comment]
it's how ae handle the rename stuffs, so sadly it can't be fixed at my side
