### ISSUE TITLE
Issue with Wireless Extended Pattern Access Terminal in ATM9 Modpack

### ISSUE THREAD

**Issue by DarkHope1988** [GlodBlock/ExtendedAE#116]
I wanted to bring to your attention an issue I've encountered with the Wireless Extended Pattern Access Terminal in the ATM9 modpack. Specifically, when I have this console in my inventory alongside the Wireless Universal Terminal from the AE2WTLIB mod, pressing the key binding to open the console only opens the Wireless Extended Pattern Access Terminal, not the one containing all the items.

Is it possible to separately assign a key combination for this or potentially make them combinable?

Thank you for your attention to this matter.

**Comment by GlodBlock** [comment]
already fixed by https://github.com/GlodBlock/ExtendedAE/commit/f271a4f3e938a494b133db8c7bdba961bde5ed9c
