### ISSUE TITLE
[Bug] ExtendedAE不在`fabric.mod.json`依赖AE2

### ISSUE THREAD

**Issue by Phoupraw** [GlodBlock/ExtendedAE#117]
一个小bug，`fabric.mod.json`的`depends`没写ae2。
（我在二分禁用模组排查bug时发现的。）

**Comment by GlodBlock** [comment]
哎fabric

**Comment by GlodBlock** [comment]
修了 https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-0.1.4-fabric
