### ISSUE TITLE
[Bug] crash when run with laest version AE2

### ISSUE THREAD

**Issue by 854342681** [GlodBlock/ExtendedAE#120]
minecraft: 1.20.1
neoforge: 47.1.100
AE2: forge-15.1.0
ExtendedAE: 1.0.19-forge

crash report: [https://paste.fastmirror.net/?a575a83c7fe60a42#69Z3qv7xmmnZGwqXPztSHAe7dU9CZXGExjqpkUM1bH6P](url)

**Comment by GlodBlock** [comment]
update to latest extendedae
