### ISSUE TITLE
[Bug] Changing the stacksize in the inscriber only applies to the input.

### ISSUE THREAD

**Issue by Kevin-Marsh** [GlodBlock/ExtendedAE#121]
Swapping the stacksize to 64 from 1 seems to only apply to the input slot. You can insert a full stack but the inscriber stops working after it processes a single item. It still shows the animation but has no progress bar and won't make any more of the craft unless you clear the output.

**Comment by GlodBlock** [comment]
fixed by https://github.com/GlodBlock/ExtendedAE/commit/b175184c3cd4c408f64a25ea1984590e3610d4d8
