### ISSUE TITLE
关于遇到的兼容性问题和一些建议

### ISSUE THREAD

**Issue by Yuyears** [GlodBlock/ExtendedAE#128]
![Clip_2024-04-05_22-32-24](https://github.com/GlodBlock/ExtendedAE/assets/145214017/fd3d2bba-e6dd-4850-b951-657429e1fee8)
这个GUI调用的光照引擎和星光（Starlight）不兼容，和星光一起使用时打开此页面会导致游戏崩溃，鉴于星光的优异性能优化，星光在各类优化模组中非常受欢迎，建议和星光模组做一下兼容

**Comment by Yuyears** [comment]
The lighting engine called by this GUI page is not compatible with the Starlight module, opening this page when using it with the Starlight module will cause the game to crash, in view of the excellent performance optimization of Starlight, Starlight is very popular among all kinds of optimization mods, and it is recommended to be compatible with the Starlight module.(Non-native English speakers, machine translation makes me feel sorry.)

**Comment by GlodBlock** [comment]
这个是因为ae和starlight不兼容，如果你非要用starlight的话加这个mod https://legacy.curseforge.com/minecraft/mc-mods/starlightxae
