### ISSUE TITLE
[Request] Applied flux - Energy accessor improvement.

### ISSUE THREAD

**Issue by Kevin-Marsh** [GlodBlock/ExtendedAE#130]
Would it be possible to have the energy accessor also act as an energy acceptor for AE? It would be awesome to have it as a bridge so that ae can draw power from internal cells.

**Comment by gjmhmm8** [comment]
建议把这玩意传输改到long，不然太慢了

**Comment by GlodBlock** [comment]
added in 1.1.5. but it is disabled by default, you need to enable it in config
