### ISSUE TITLE
[Request] Please add extended version of memory card 

### ISSUE THREAD

**Issue by LunaeKim99** [GlodBlock/ExtendedAE#134]
If it possible could you add extended version of memory card like in this mod :
https://www.curseforge.com/minecraft/mc-mods/betterp2p

![showcase1](https://github.com/GlodBlock/ExtendedAE/assets/125992636/e52f7788-d37b-4137-99b0-5bfbb0c30f7b)
<img width="641" alt="showcase3" src="https://github.com/GlodBlock/ExtendedAE/assets/125992636/5147459b-d52f-4774-a5a0-44e0dd7b82ac">

<img width="188" alt="showcase0" src="https://github.com/GlodBlock/ExtendedAE/assets/125992636/f57af796-ffbb-4cfc-b72c-7282d599cd73">

**Comment by GlodBlock** [comment]
duplicate with https://github.com/GlodBlock/ExtendedAE/issues/45
