### ISSUE TITLE
通量访问点兼容Long

### ISSUE THREAD

**Issue by gjmhmm8** [GlodBlock/ExtendedAE#137]
https://github.com/GlodBlock/ExtendedAE/pull/135
在加了通量网络的情况下就能跑到long了，mek也行，测试过的

**Comment by gjmhmm8** [comment]
兼容通量网络应该是算去到long最方便的了

**Comment by GlodBlock** [comment]
你这个叫兼容通量网络，不叫支持long，还有你代码写的也很不行

**Comment by gjmhmm8** [comment]
你写的行你写，兼容到Long就行

**Comment by gjmhmm8** [comment]
不管怎么说，至少能用了

**Comment by gjmhmm8** [comment]
而且你循环嵌套成那个样，也不见得有多好

**Comment by GlodBlock** [comment]
你代码耦合度太高了，我准备抽象一个外部接口出来处理可以接受long io的mod，这样后面做其他mod的兼容就很方便

**Comment by gjmhmm8** [comment]
你的mod，你看着办

**Comment by gjmhmm8** [comment]
最终能兼容就行

**Comment by asdflj** [comment]
赞美 glodblock

**Comment by GlodBlock** [comment]
加了
