### ISSUE TITLE
ui界面升级槽被网络工具的槽位挡住

### ISSUE THREAD

**Issue by asdflj** [GlodBlock/ExtendedAE#138]
![image](https://github.com/GlodBlock/ExtendedAE/assets/33802162/a9630144-cada-40a8-a8b4-e56f20b7e184)
![image](https://github.com/GlodBlock/ExtendedAE/assets/33802162/61d43809-0d7e-4789-8822-98b821adbb90)

**Comment by asdflj** [comment]
@GlodBlock

**Comment by asdflj** [comment]
人呢

**Comment by GlodBlock** [comment]
别急

**Comment by asdflj** [comment]
![76868c1ba46f9eba06e7da35b0a3497c](https://github.com/GlodBlock/ExtendedAE/assets/33802162/41028e9a-84ed-4b06-8e5f-04e663e8f681)

**Comment by asdflj** [comment]
![77828c03c8beb3d6ec9b8bcaf36aa17b](https://github.com/GlodBlock/ExtendedAE/assets/33802162/6eeb7fa8-99fa-486c-b555-9c714de1209d)

**Comment by GlodBlock** [comment]
修了
