### ISSUE TITLE
Interaction with Sophisticated Storage causing Crash to Desktop

### ISSUE THREAD

**Issue by Affront7546** [GlodBlock/ExtendedAE#141]
### Describe the bug

Occasionally the game will crash with a "Ticking GridNode" error.
This has occurred on All The Mods 9, versions 0.2.56 and 0.2.57.
- 0.2.56 the crash occurred after the game was running for a couple of hours.
- 0.2.57 the crash occurred within 10 seconds after the game loaded.

### Minecraft version

1.20

### On which mod loaders does it happen?

Forge

[All The Mods 9 Version 0.2.57](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5282232)

### Crash log

[crash-2024-04-24_09.05.55-server.txt](https://github.com/GlodBlock/ExtendedAE/files/15098443/crash-2024-04-24_09.05.55-server.txt)

[crash-2024-04-24_12.22.40-server.txt](https://github.com/GlodBlock/ExtendedAE/files/15098444/crash-2024-04-24_12.22.40-server.txt)

**Comment by GlodBlock** [comment]
it is sophisticated storage's issue. you should post this to their issue page
