### ISSUE TITLE
[Suggestion] An import/export bus with integrated level emitter

### ISSUE THREAD

**Issue by Kevin-Marsh** [GlodBlock/ExtendedAE#142]
Right now using level emitters are bulky. You need a level emitter/bus pair for each individual item. A bus that has the redstone/emitter control built into it would allow for more compact setups. This could potentially be an alternate mode on the precise buses were you insert a card to change to this mode and you can then set the number and if you want it to work above or below this number.

**Comment by GlodBlock** [comment]
thatn sounds like me requester's job

**Comment by Kevin-Marsh** [comment]
Whilst this would be an excellent method for keeping stock of items it isn't what I had initially thought the use for this would be. My main thought was for things like automated factories where you want to be able to run certain process lines when you have more than a set amount of resources or for things like automating blood magic slates where it would require 5 different buses each with a  level emitter crafting card to import from the craft.

**Comment by GlodBlock** [comment]
added in 1.1.4
