### ISSUE TITLE
Crash when opening guide book

### ISSUE THREAD

**Issue by hgjensen** [GlodBlock/ExtendedAE#144]
Trying to open ae2 guide-book for the caner and crystal-fixer from ExtendedAE (by hovering icon ang holding G) causes the game to crash.
[crash-2024-04-26_07.54.18-client.txt](https://github.com/GlodBlock/ExtendedAE/files/15127835/crash-2024-04-26_07.54.18-client.txt)

Version: ExtendedAE-1.20-1.1.2-forge.jar

**Comment by GlodBlock** [comment]
because starlight is incompatible with ae. you need to remove starlight or add this patch mod https://www.curseforge.com/minecraft/mc-mods/starlightxae
