### ISSUE TITLE
希望能加入类似Lazier AE2里电路板蚀刻器的机器

### ISSUE THREAD

**Issue by TheDesiringOne** [GlodBlock/ExtendedAE#147]
这个mod非常好用，解决了很多我使用ae时的难题;唯有一个地方是希望改进的：扩展压印器虽然变成了四线程，但自动化还是有些繁琐，希望能在这个机器的基础上做个升级，变成类似Lazier AE2里电路板蚀刻器的机器，只要输入相应的原料，就能输出成品，贵些也没事；当然如果大佬怕撞车，那就算了吧，不管怎么说，还是谢谢大佬的贡献了。

**Comment by GlodBlock** [comment]
和layzier ae2作者谈过这个事情，他说不希望我加，并且layzier ae2的高版本正在做
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/1fcb967b-daab-495b-bfe4-1ae0100d7b50)

**Comment by TheDesiringOne** [comment]
emm，好吧，不过大佬就算更新1.19版本，我又是玩1.20.1版本的；希望能尽快更新吧，谢谢回应了。
