### ISSUE TITLE
[New Feature/Suggestion] Extended Level Emitter

### ISSUE THREAD

**Issue by TuotHash** [GlodBlock/ExtendedAE#148]
Add a Level Emitter with more slots.
![image](https://github.com/GlodBlock/ExtendedAE/assets/78159339/1d196fee-d5fb-4b33-b70b-de3b8bd72aa6)
There are many cases where multiple level emitters are needed and cram up the place.

**Comment by GlodBlock** [comment]
you can use threshold export bus if you want to control export bus with multiple level emitters.
