### ISSUE TITLE
Applied Flux-FE gets pulled into the network with import bus

### ISSUE THREAD

**Issue by Torben4** [GlodBlock/ExtendedAE#150]
Modpack: ATM9

if you place a import bus on some machines (for example the Pulverizer from Thermal Series) the import bus will import the internal energy buffer of that machine. That isnt a expected behavior and just pumps the energy in cycles. Due to FE not being listed in JEI or available as item i wasnt able to filter the import except for the mod variant of the storage bus and building subnets for everything. Maybe its possible to list FE in JEI.

**Comment by GlodBlock** [comment]
you can filter fe with anything contains energy: battery, electricity tools, etc.
i will disable me import bus draining fe (configurable) in next update

**Comment by Torben4** [comment]
my bad, didnt notice the option to filter fe with right klick and a tool, thanks for the fast reply :)

**Comment by GlodBlock** [comment]
fixed in 1.1.6 https://legacy.curseforge.com/minecraft/mc-mods/applied-flux/files/5306998
