### ISSUE TITLE
Infinity lava cell

### ISSUE THREAD

**Issue by JEEEBZ1** [GlodBlock/ExtendedAE#152]
Possible add an Infinity Lava cell like how there is a cobble and water cell?

**Comment by gjmhmm8** [comment]
you can add it by kubejs or nbt

**Comment by JEEEBZ1** [comment]
i play on a server

**Comment by GlodBlock** [comment]
you add it in config but it won't be added by default

**Comment by JEEEBZ1** [comment]
and for the crafting recipe of it?
