### ISSUE TITLE
[功能请求]添加样板接口二合一终端

### ISSUE THREAD

**Issue by asdflj** [GlodBlock/ExtendedAE#159]
![image](https://github.com/GlodBlock/ExtendedAE/assets/33802162/0b3078d8-40dc-4efd-835e-7868316aac25)
突然有个奇思妙想 @GlodBlock 
这样就不用每次写完样板还要打开接口终端放样板了

**Comment by GlodBlock** [comment]
不是有通用终端mod吗

**Comment by asdflj** [comment]
这个不用切换

**Comment by GlodBlock** [comment]
这个ui极其大便，我不太想再碰

**Comment by asdflj** [comment]
![eee628b1588a733f93fb43dea216fd45](https://github.com/GlodBlock/ExtendedAE/assets/33802162/479a3bd1-ac9c-4904-8256-10370a2ee283)
