### ISSUE TITLE
[Feature Request] Wireless Requester Terminal

### ISSUE THREAD

**Issue by heisluft** [GlodBlock/ExtendedAE#161]
ExtendedAE has wireless terminals for all terminals but the requester terminal as of now. Adding it would make it possible to have all ME features on the fly.

**Comment by GlodBlock** [comment]
nah, extendedae doesn't add wireless terminals. the wireless terminal mod is https://github.com/Mari023/AE2WirelessTerminalLibrary

**Comment by heisluft** [comment]
tracked in https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/269
