### ISSUE TITLE
[建议] 改进样板修改器乘数

### ISSUE THREAD

**Issue by Phoupraw** [GlodBlock/ExtendedAE#163]
把样板修改器的乘数由2, 10改为2, 3, 5, 7等质数。
把乘和除合并为一个按钮，左键乘，右键除，以节省空间。

**Comment by asdflj** [comment]
啊?

**Comment by Phoupraw** [comment]
![image](https://github.com/GlodBlock/ExtendedAE/assets/50520903/f15a99f2-f3b9-4624-88d7-231851c3b5bc)

**Comment by GlodBlock** [comment]
用素数有什么说法吗，我选2和10是因为用的多

**Comment by Phoupraw** [comment]
素数可以组合出其它的数，但是其它的数不能组合出素数，比如现在的2和10就只是相当于2和5，只能乘2, 4, 5, 8, 10, 16, 20, 25, 32等倍数，如果要乘3, 7, 9等数就做不到。

**Comment by GlodBlock** [comment]
一般来说用不到x3和x7这种操作，而x10和x2用的最多，全换成素数的话我x10就要按两次按钮，从用户角度来说反而是不方便的

**Comment by Phoupraw** [comment]
啊？为什么说一般来说用不到x3和x7这种操作？我玩格雷科技，恨不得把质数全加上

**Comment by Phoupraw** [comment]
那可以搞个自定义设置吗？用户可以自己选择乘数。

**Comment by GlodBlock** [comment]
gt里用x3x7的情况吗，我玩nomi和nh的时候只用过x2

**Comment by Phoupraw** [comment]
如果原本是3/7/9，那么需要增加到63（不能超过64），就需要乘21/9/7；如果原本是5，那么需要增加到60，就需要乘12；流体的情况就更多，而且由于相同流体不能同时存在多个格子里，所以限制还要更严格。

**Comment by GlodBlock** [comment]
行

**Comment by asdflj** [comment]
我看行

**Comment by asdflj** [comment]
自定义就很好

**Comment by gjmhmm8** [comment]
感觉还不如输个数直接乘，再加个一键除最大公约数的

**Comment by GlodBlock** [comment]
加了

**Comment by Phoupraw** [comment]
这项改动会更新到1.20.1 forge吗？
