### ISSUE TITLE
Extended inscribers do not start production automatically. 

### ISSUE THREAD

**Issue by NTXSTEALTH** [GlodBlock/ExtendedAE#164]

**Comment by NTXSTEALTH** [comment]
Extended inscribers do not start production sometimes and need to be updated by removing an item and placing it back.

**Comment by GlodBlock** [comment]
huh, why close the issue?

**Comment by NTXSTEALTH** [comment]
hey sorry to close the issue, without an proper statement,
After some research it turns out it was caused by the update to AE2 at that time and has been fixed, i apologize for raising an issue.
