### ISSUE TITLE
[Request] or [Idea] for Extended Blocks/Machines 

### ISSUE THREAD

**Issue by ghost** [GlodBlock/ExtendedAE#17]
Hi I have ideas or request for additional machines or blocks which could improve the mod even more.

On the one hand it would be an improved Charger with which you can charge several Certus Quartz Crystals at the same time.
On the other hand it would be an improved Inscriber with which you can craft several processors at the same time.
In other words, like the Extended Molecular Assemblers so that you can do several jobs at the same time.

It's just an idea, if it's not possible, not wanted or planned, it's fine.

**Comment by GlodBlock** [comment]
they will be added later

**Comment by GlodBlock** [comment]
added now https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-0.1.23-forge
