### ISSUE TITLE
game will crash when right click ex_provider_terminal search bar

### ISSUE THREAD

**Issue by DancingSnow0517** [GlodBlock/ExtendedAE#171]
https://github.com/GlodBlock/ExtendedAE/blob/1.20.4-neoforge/src/main/java/com/glodblock/github/extendedae/mixins/MixinScreen.java#L22

The crash was maybe caused by here.

[crash-2024-06-04_00.45.58-client.txt](https://github.com/user-attachments/files/15537126/crash-2024-06-04_00.45.58-client.txt)

**Comment by GlodBlock** [comment]
修了
