### ISSUE TITLE
[help wan't] mod added provider machine not show on ex_patten_terminal

### ISSUE THREAD

**Issue by DancingSnow0517** [GlodBlock/ExtendedAE#172]
in ae2's patten access terminal
![image](https://github.com/GlodBlock/ExtendedAE/assets/60736156/faaf1e46-d44a-443d-bb5d-a3137cfcdae7)
in extendedae's patten access terminal
![image](https://github.com/GlodBlock/ExtendedAE/assets/60736156/01bb2355-09e0-4265-8550-92a553ef8a5b)
Not displayed any slot
need help how to add it to the terminal

**Comment by GlodBlock** [comment]
修了
