### ISSUE TITLE
[Future Request/Pull Request] Allow multiple mods to be filtered in the Mod Storage Bus

### ISSUE THREAD

**Issue by WexalianMC** [GlodBlock/ExtendedAE#176]
I have noticed that if you wanna filter more than 1 mod into a single chest, the cable-ing can get really tedious having a subnet to add all Mod Storage Busses to.

Just now, I have been able to fork and modify your source so that you can use a comma character to filter based on multiple mods.

But now I was wondering, maybe this can be intergrated into the main mod, if this is what you want of course.
I understand if you want to keep it at 1, but maybe then we can have an Extended Mod Storage Bus?

Let me know and I'll make a pull request!

(sorry if this is unneccessary, just let me know)

**Comment by GlodBlock** [comment]
sure, you can make a pull request, but i have a few questions:
1. what if a mod use comma in their mod id or mod name?
2. do you also add input suggestion support when it comes to multipe mod inputs?

**Comment by WexalianMC** [comment]
1) Using a comma in a mod id is not allowed, according to the Forge docs a mod id has to be "a string 2-64 characters; starts with a lowercase letter; made up of lowercase letters, numbers, or underscores", so that won't be a problem.

2) Yes, I have made it so that the suggestions will exclude the mod ids that came before in the line.

**Comment by GlodBlock** [comment]
that's good. i am waiting for your pull request
