### ISSUE TITLE
[Feature Request] Export Bus Induction Card

### ISSUE THREAD

**Issue by therocki** [GlodBlock/ExtendedAE#178]
It would be nice if the induction card also worked on the export bus. It would make sense since it would be like you're also exporting power. This may already be planned since this is a relatively new item.

**Comment by GlodBlock** [comment]
you can mark energy in export bus to output power
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/6b066ba2-1b76-4afd-b585-728924e5f6d9)
right click with anything contains power to mark energy (like battery, electrical tools)

**Comment by therocki** [comment]
Oh, okay, thank you!
