### ISSUE TITLE
Modpack crash

### ISSUE THREAD

**Issue by SANCHEI** [GlodBlock/ExtendedAE#179]
Aded mod to modpack  version 1.19.2 with forge 43.2.8 and then got crash. Error code -1

Crash report:
[crash-2024-06-12_01.57.53-fml.txt](https://github.com/user-attachments/files/15826108/crash-2024-06-12_01.57.53-fml.txt)

**Comment by GlodBlock** [comment]
i see extendedae isn't installed in your crash report. are you sure it is caused by my mods?
it looks like jerintegration is crashing, so i suggest you report the crash to their [github page](https://github.com/Janoeo/JER-Integration)

**Comment by SANCHEI** [comment]
https://github.com/GlodBlock/ExtendedAE/assets/62657179/191848a0-9db1-496b-b333-5902582bc0e2

**Comment by SANCHEI** [comment]
If i turn off or remove ExtendedAE mod modpack starts up properly.
Here is a latest log file:
[latest.log](https://github.com/user-attachments/files/15844839/latest.log)

**Comment by GlodBlock** [comment]
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/3d745db1-0fdb-40c5-9ab9-a4729d8c0741)
you need to upgrade ae2 to 12.9.5 or higher

**Comment by SANCHEI** [comment]
Yes, fixed thx.
