### ISSUE TITLE
Can't set amount in ME Threshold Export Bus using middle mouse click

### ISSUE THREAD

**Issue by EdgeHallow** [GlodBlock/ExtendedAE#180]
Playing in ATM9-Sky, unable to use my middle mouse button to set a custom amount with the threshold export bus. I can increment the amount by left/middle clicking with a stack of items, and decrement using right click too.

**Comment by GlodBlock** [comment]
it is a keybind issue. inventory tweaker's item sort also uses middle click so it won't work for ae's. you can set its keynbind to other hotkey or just unbind it.
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/0e9e63c5-8795-4182-b80a-8b98b60881b9)

**Comment by schneiderchristopher** [comment]
The issue still remains even when removing the keybing, I removed every related middle click keybing and still does not work, also there's no option to configure another key to change those values

**Comment by schneiderchristopher** [comment]
https://github.com/GlodBlock/ExtendedAE/blob/9239554b1d3617516ac98ea563354fdc81c31bc6/src/main/java/com/glodblock/github/extendedae/client/gui/GuiPreciseStorageBus.java#L98

I see what my problem was, you are using the default keybind of minecraft to pick up items, I removed this so this was no longer working...

I see this is also the case for the AE2 lol, maybe better to use another option to take this key event?

**Comment by GlodBlock** [comment]
i think you shouldn't change vanilla mc keybind at most time. maybe in future i will add an another keybind for this action
