### ISSUE TITLE
Pattern Provider uses only 1 Extended Molecular Assembler, also Extended Molecular Assembler now work properly 

### ISSUE THREAD

**Issue by V4kodin** [GlodBlock/ExtendedAE#181]
For some reason, Pattern Providers can't use more than 1 Extended Molecular Assembler.
<details>
  <summary>only 1 Extended Molecular Assembler uses demonstration</summary>

![2024-06-16_06 48 49](https://github.com/GlodBlock/ExtendedAE/assets/61556245/f1678ae4-0bfb-4236-b1af-e8f820081471)
</details>

Usually it's not a big issue (some time it's even an advantage) cause Extended Molecular Assembler has 8 craft slots.
But for some reason, my Extended Molecular Assembler also can't craft Essence from mod [Mystical Agriculture](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture) at more than 1 crafting job of Assembler. 
<details>
  <summary>only 1 crafting job of Assembler demonstration</summary>

![2024-06-16_07 18 02](https://github.com/GlodBlock/ExtendedAE/assets/61556245/0bb82372-6db4-45ca-968c-00ae4b35eb45)
![2024-06-16_07 14 29](https://github.com/GlodBlock/ExtendedAE/assets/61556245/17db4307-0af3-451f-b968-2a9b67920355)
</details>

That's a big problem cause this mod need literary hundred thousands crafting operations. 

Also, you may think the issue is "Master Infusion Crystals" that used for essence craft, as I thought so, but unfortunately it's not, because I have 6 of them in my me network and still have only 1 crafting job work at the time.

So crafting took plenty of time.
<details>
  <summary>crafting time</summary>

![image](https://github.com/GlodBlock/ExtendedAE/assets/61556245/30a805c3-4764-4156-95ba-72b2543ffa15)
</details>

If any information needed, just ask.
I used [this version of atm9](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5378700) at my game. (ExtendedAE 1.20-1.17-forge)

**Comment by GlodBlock** [comment]
do you have co-processors in your me network

**Comment by V4kodin** [comment]
> do you have co-processors in your me network

Yeah, ass you can see in last screenshot I have 6 co-processors

**Comment by GlodBlock** [comment]
well, it is an ae2 issue. their recipe calculator logic only uses one crystal if it isn't consumed. so you need to report the issue to their github issue page.
btw, i suggest you use other mods crafter (like rftools's crafter) when it comes to non-consume item recipe

**Comment by V4kodin** [comment]
> well, it is an ae2 issue. their recipe calculator logic only uses one crystal if it isn't consumed. so you need to report the issue to their github issue page.
> btw, i suggest you use other mods crafter (like rftools's crafter) when it comes to non-consume item recipe

Ok, I ll do it, thx pal. 

I appreciate your work.
