### ISSUE TITLE
no crafts

### ISSUE THREAD

**Issue by MehanikTMYT** [GlodBlock/ExtendedAE#182]
1.20.4 neoforge
version of mod - 1.20-2.0.0-neoforge
no crafts for jei in: concurrent processor, inscriber concurrent press (maybe it will find in meteors, i don't know), printed concurrent circuit, ME extended Pattern Provider,  ME extended interface,  ME extended Export bus,  ME extended import bus, ME active Formation plate, ME oversize interface, Extended inscriber, Extended charger, crystall fixer, ME cander, ME extended IO port, Circuit Slicer, ME Extended pattern terminal

**Comment by GlodBlock** [comment]
jei isn't supported by ae2 any more, you need to use emi.

**Comment by MehanikTMYT** [comment]
in emi it will work well?

**Comment by GlodBlock** [comment]
yea
