### ISSUE TITLE
question

### ISSUE THREAD

**Issue by MehanikTMYT** [GlodBlock/ExtendedAE#184]
how to automanizate creation of entro crysyals? annihilation plate destroy all types and no creating entro

https://github.com/GlodBlock/ExtendedAE/assets/29605858/92673548-34c9-473d-b88d-1c1a8dd889ec

**Comment by GlodBlock** [comment]
you need to setup a subnet for annihilation plate with **silk touch** that only can store entro cluster. then place the entro cluster with formation plane and haverst it with normal annihilation plate.
an example setup is like this:
![40618205708](https://github.com/GlodBlock/ExtendedAE/assets/60341015/cdbe14e1-7800-483a-b6af-917a21c7b25f)
