### ISSUE TITLE
[Bug] ME Tag Export Bus doesn't move stacks in certain situations.

### ISSUE THREAD

**Issue by DeeJayhX** [GlodBlock/ExtendedAE#187]
~~I don't know if it is a result of the Exporter refusing to move a stack of items~~, or **the Enchantment Library from Apotheosis refuses to accept a stack of items**, but the ME Tag Export Bus is allowing books to pile up in my inventory because they are not being inserted one at a time; see image. If I remove all, but one, of a particular book, the ME Tag Export Bus will pick it up and place it into the Enchantment Library, and if I continue to add them back one at a time, it will continue to take them one at a time, but once that "stack" hits 2 or more, it no longer works. Filter is `forge:books`, which works perfectly for any single enchanted book since the exporter is pointed directly at the library.

**Addendum,** it *is* the library's fault, as removing all of the acceleration cards means the ME Tag Export Bus can only move one item at a time, and it begins working again. Perhaps there can be a 1/64 button added to the ME Tag Export Bus, like inscribers have, so that it can be set to 1 and move 1 item at a time very quickly with 4 acceleration cards? Not sure if this is still a bug or an enhancement at this point.

<img width="412" alt="image" src="https://github.com/GlodBlock/ExtendedAE/assets/1514573/a7a85eb6-402b-4094-88e6-fc394f623042">

**Comment by GlodBlock** [comment]
that's apotheosis library issue. the export bus works when it push multiple books to other item containers like chest.
you can report this problem to apotheosis github

**Comment by DeeJayhX** [comment]
> that's apotheosis library issue.

I agree, but just to restate, you could overcome the limitations of any mod with this issue, not just Apotheosis, by adding a 1 or 64 toggle like inscribers have to allow us to force the bus to do 1 item at a time, but in quicker intervals when using acceleration cards. 

Feel free to close this issue if you're not interested or decide to go ahead with that enchantment and move it to its own ticket.

Either way, thanks for your time!

**Comment by GlodBlock** [comment]
> in quicker intervals when using acceleration cards.

that can't be done under ae's architecture, otherwise it will cause huge lag
