### ISSUE TITLE
[Feature Request] 在终端中存取fe时无视物品能量输入输出上限

### ISSUE THREAD

**Issue by 0O0OwO0O0** [GlodBlock/ExtendedAE#188]
对于有充电速度限制的物品，需要在终端中一直点击才能充电，希望添加在终端中按住shift存取fe时无视物品能量输入输出上限的功能，或在按住shift存取时视为连续进行多次存取以实现这一目的，对于部分流体容器在进行流体存取也有类似的存取不便问题，另外，可以顺便添加无限能量的创造元件

**Comment by asdflj** [comment]
![314db052c1847c0b51794ce3eff22482](https://github.com/GlodBlock/ExtendedAE/assets/33802162/38881e37-0a86-4f2c-b549-18aec5e3d241)

**Comment by GlodBlock** [comment]
后面会尝试加

**Comment by GlodBlock** [comment]
ae1.21按住shift就能一次性清空/装满容器了，所以这里就不用再加了
