### ISSUE TITLE
Circuit Slicer doesnt seem to work

### ISSUE THREAD

**Issue by cauliflower69** [GlodBlock/ExtendedAE#189]
Using version ExtendedAE-1.20-2.0.0-neoforge.

I cant seem to get the circuit slicer to do anything.

Also using emi-1.1.7+1.20.4+neoforge no recipes are showing up?

There is a guide but it appears to be broken https://imgur.com/a/OU7iBom

Using the FTB neotech modpack

**Comment by GlodBlock** [comment]
neotech removed the circuit slicer's recipe, and you need to use mi machine to craft it
