### ISSUE TITLE
[Bug] Opening a provider with a networking tool in your inventory crashes

### ISSUE THREAD

**Issue by Kevin-Marsh** [GlodBlock/ExtendedAE#197]
Placing a networking tool into your inventory and right clicking a pattern provider crashes to the main menu. It has to be in your inventory but not being held to do it. This behaviour isn't present without Applied Flux installed.

[Logs](https://mclo.gs/HIutbef)
Neoforge: 21.0.57
Minecraft: 1.21
Applied Energistics: 19.0.8
Applied Flux: 1.21-1.0.1

**Comment by GlodBlock** [comment]
fixed in 1.0.2
