### ISSUE TITLE
Wireless Connector crashes client when rendering Integrated Dynamics parts

### ISSUE THREAD

**Issue by Jmpp2909** [GlodBlock/ExtendedAE#199]
**Version**: ExtendedAE-1.20-1.1.10-forge.jar
**Modpack of occurrence**: ATM9 To The Sky - 1.0.6
Problem: if a Wireless Connector has Integrated Dynamics parts nearby, when Right Clicking the pair of it, it will crash when trying to render the area around it.

I recreated it in a singleplayer world, check below:
![image](https://github.com/GlodBlock/ExtendedAE/assets/129900104/987e9081-e131-4a48-90f7-a4e0f31a1400)

Connector 1:
![image](https://github.com/GlodBlock/ExtendedAE/assets/129900104/277da061-845f-4ce6-969c-dfa5006103fe)
![image](https://github.com/GlodBlock/ExtendedAE/assets/129900104/4de4c33f-57d4-4b53-a5f5-6f7e0005da0a)
When right clicking it: ![image](https://github.com/GlodBlock/ExtendedAE/assets/129900104/bae98640-0cf8-42be-9336-baa91bee8493)

Connector 2:
![image](https://github.com/GlodBlock/ExtendedAE/assets/129900104/4665bdfd-a047-4cf3-8254-41a20b1d5150)

when right clicking it: (crashed) https://mclo.gs/KTWAfYK

**Comment by GlodBlock** [comment]
fixed in 1.1.11
