### ISSUE TITLE
Induction card causes massive lag while in a pattern provider 1.21

### ISSUE THREAD

**Issue by VoidTest** [GlodBlock/ExtendedAE#200]
I had pattern providers with an induction card with rainbow furnaces around it and the tps was tanking. When i checked the pattern provider was filled with Forge Energy idk how bc the furnace should not be able to output energy.

This happened on ATM 10-0.7

**Comment by GlodBlock** [comment]
i think rainbow furnace can output energy from its tooltip?
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/2edadfb9-db19-49d7-b3b8-87c8d235773a)
as to the tps issue, do you have the spark profiler link?

**Comment by GlodBlock** [comment]
should has been fixed in 1.1.2
