### ISSUE TITLE
[Suggestion] Retire the extended inscriber and craft processors in the Crystal Assembler

### ISSUE THREAD

**Issue by Kevin-Marsh** [GlodBlock/ExtendedAE#203]
The Circuit Cutter allows for fast circuit crafting. The inscriber however is far slower. The creation of the cutter however presents the possibility to use the cutter for the base ingredients and the Crystal Assembler for the final assembly. This will massively speed up the creation of processors and create a similar crafting path to the old mods like lazierae2.

I would also like to tack on the suggestion of crafting sky steel with lava in the Assembler.

Edit: I datapacked in the recipes and it appears that the crystal assembler can produce a stack of processors in 16 seconds. It is equal speed to the extended inscriber while needing less pieces since you can just have them run through your existing infrastructure.

**Comment by GlodBlock** [comment]
added. mega support will come out when 90 releases mega

**Comment by GlodBlock** [comment]
mega support is added in latest
