### ISSUE TITLE
AE2WirelessTerminalLibrary(AE2WTLib)  incompatibility

### ISSUE THREAD

**Issue by MrChuw** [GlodBlock/ExtendedAE#209]
Crash when trying to open the game with AE2WTLib

NeoForge version: 21.0.95
AE2WTLib version: 19.0.10-beta (I tried with all available versions.)
ExtendedAE version: 1.21-1.1.0-neoforge (I tried with all available versions.)

[crash-2024-07-15_22.51.53-fml.txt](https://github.com/user-attachments/files/16242182/crash-2024-07-15_22.51.53-fml.txt)

**Comment by GlodBlock** [comment]
fixed in 1.1.1
