### ISSUE TITLE
New Feature Request 

### ISSUE THREAD

**Issue by elijahward** [GlodBlock/ExtendedAE#21]
I would love to extend fuzzy card. Adding export by tag, mod, etc. 

I'm not sure if this were request can be filed

**Comment by GlodBlock** [comment]
card logic isn't easy to extend, so i won't add a new card for it but add another eport/storage bus with the same function for it.

**Comment by GlodBlock** [comment]
added in https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-0.1.28-forge

**Comment by elijahward** [comment]
Thank you. I look forward to the update

Elijah Ward
