### ISSUE TITLE
[suggestions]在合成终端合成时支持流体参与合成（类似于分子装配室使用流体代替）（比如在工作台用对应流体桶合成时实际消耗对应的流体而不是将流体桶变为空桶）

### ISSUE THREAD

**Issue by 0O0OwO0O0** [GlodBlock/ExtendedAE#210]
1.在合成终端合成时支持流体参与合成（类似于分子装配室使用流体代替）（比如在工作台用对应流体桶合成时实际消耗对应的流体而不是将流体桶变为空桶）
2.添加类似functional storage的军械柜这样仅可存储不可堆叠物品，但不限类的存储元件，或添加相应的元件工作台过滤选项（有AE2 Things的深度驱动器不限类，但一字节只能存一个物品，效率低，方便过滤）

**Comment by 0O0OwO0O0** [comment]
另外，扩展样板管理终端有bug 当样板供应器连接两不同机器时，在样板管理终端鼠标移到对应样板供应器时会显示相邻机器提示框，而在扩展样板管理终端中这个提示框会错位，会发生显示错位

**Comment by GlodBlock** [comment]
> 1.在合成终端合成时支持流体参与合成（类似于分子装配室使用流体代替）（比如在工作台用对应流体桶合成时实际消耗对应的流体而不是将流体桶变为空桶） 2.添加类似functional storage的军械柜这样仅可存储不可堆叠物品，但不限类的存储元件，或添加相应的元件工作台过滤选项（有AE2 Things的深度驱动器不限类，但一字节只能存一个物品，效率低，方便过滤）

这个我其实觉得更合适直接放在ae本体而不是附属里，你去ae那边提一下

> 另外，扩展样板管理终端有bug 当样板供应器连接两不同机器时，在样板管理终端鼠标移到对应样板供应器时会显示相邻机器提示框，而在扩展样板管理终端中这个提示框会错位，会发生显示错位

最新版修了
