### ISSUE TITLE
[Bug] ExtendedAe seems to be causing an issue with update recipes.

### ISSUE THREAD

**Issue by Kevin-Marsh** [GlodBlock/ExtendedAE#214]
Having extendedAE installed is causing EMI to hang and the game to not be able to run update recipes due to:
java.lang.IllegalArgumentException: BlockBuddingEntro[entro_budding_half] has been used in other crystal fixer recipe
https://mclo.gs/MLyTsF6#L811

**Comment by GlodBlock** [comment]
fixed in 1.1.3
