### ISSUE TITLE
Extended Interface, Oversized Interface and Pattern provider display an enormous Jade tooltip

### ISSUE THREAD

**Issue by ym0ka** [GlodBlock/ExtendedAE#215]
As shown on the screenshot below, the following items display a much bigger tooltip than it probably should when using Jade.
- ME Extended Interface
- ME Oversized Interface
- ME Extended Pattern Provider

![image](https://github.com/user-attachments/assets/313540b8-1749-4fcb-a67e-de3dcbdddab2)

Mod version : 1.1.3 on Neoforge
Tested on ATM 10 v0.16

**Comment by GlodBlock** [comment]
that is applied mekanistics issue. please post to their github page
