### ISSUE TITLE
Mekanism removed a FloatingLong method that AppFlux depends on 

### ISSUE THREAD

**Issue by djnifos** [GlodBlock/ExtendedAE#216]
If this is the wrong place, sorry, I just followed the curseforge link here.

https://mclo.gs/DNVKN6V

ver 1.1.2-neoforge.jar

mek v 10.6.6.53

https://github.com/mekanism/Mekanism/commit/9c21d943e65277231cffb2f739a246b047cbda20#

**Comment by GlodBlock** [comment]
fixed in the latest
