### ISSUE TITLE
Is there any plans for a fabric 1.20.1 release?

### ISSUE THREAD

**Issue by levicc00123** [GlodBlock/ExtendedAE#22]
I loved having extendedAE for 1.19.2 fabric, especially when playing with Tech Reborn, that I was honestly surprised a fabric version hasn't been released yet for 1.20.1.

**Comment by GlodBlock** [comment]
released now https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-0.1.0-fabric

**Comment by levicc00123** [comment]
Thank you very much!
