### ISSUE TITLE
When creating an assembler matrix I need to reload the world for it to show the correct number of patterns

### ISSUE THREAD

**Issue by ArginEridark** [GlodBlock/ExtendedAE#220]
I've created a 5x5 and 7x7 matrix. Both of these matrixes showed 45 recipes with only 36 working. I had 24 recipe cores in the 7x7 and 5 in the 5x5. they would only show all the available recipe slots after closing and reopening the world.

**Comment by ArginEridark** [comment]
I also can't put patterns in random rows sometimes.

**Comment by GlodBlock** [comment]
fixed by https://github.com/GlodBlock/ExtendedAE/commit/c5bada34711da347137a5578856d586897b740eb
