### ISSUE TITLE
把鼠标移动到封包上会闪退

### ISSUE THREAD

**Issue by Remering** [GlodBlock/ExtendedAE#222]
# 使用的版本
+ Minecraft: `1.20.1`
+ Forge: `47.3.5`
+ ExtendedAE: `1.20-1.1.11-forge`
# 如何复现
1. 安装并打开[GregTech Leisure 1.3.1.10](https://www.123pan.com/s/LDeAjv-EHZ03)整合包
2. 编写任意封包样板
3. 将鼠标移动到封包上来查看详情
4. 客户端崩溃
# 错误报告
在[这里](https://github.com/Remering/pastebins/blob/main/crash-2024-07-28_15.04.28-client.txt)

**Comment by GlodBlock** [comment]
修了
