### ISSUE TITLE
When im opening the Exteneded Inscriber it kicks me to the tiel screen

### ISSUE THREAD

**Issue by Gh3ttoboy** [GlodBlock/ExtendedAE#225]
when i try to open the extended inscriber i keep getting this error and it boots me back to the main menu i am on the ATM 10 pack and there latest update all the mods 10-0,24 i will also post this to the Allthemods discord because it might just be an issue with the ATM 10 pack instead of ExtendedAE

[The Error in question](https://cdn.discordapp.com/attachments/345948820150026243/1269273756354740224/image.png?ex=66af76cd&is=66ae254d&hm=6a67521606776519c0916c4689c539fbebafbc879470dc7d50237b491277343b&)

**Comment by GlodBlock** [comment]
use the latest one, it has been fixed
