### ISSUE TITLE
[1.21 Issue] Assembler Matrix building rules appear to be wrong or not followed

### ISSUE THREAD

**Issue by DawnFayrie** [GlodBlock/ExtendedAE#227]
Mod Version: 1.2.1, In ATM10 Modpack

In the ingame guide it states the the matrix is a rectangular prism with side lengths of 3 to 7, yet when attempting to build one that is 4x4 blocks and 3 blocks tall the matrix refuses to form following all other guidelines for it. When making this structure a solid 4x4x4 it forms immediately with no issues.

With a bit more testing as well, the matrix seems to not form at all if only 3 high and all other building guidelines being followed.

**Comment by GlodBlock** [comment]
fixed
