### ISSUE TITLE
Are there plans to update the 1.19.2 ver mod?

### ISSUE THREAD

**Issue by blaiddes** [GlodBlock/ExtendedAE#23]
Been loving the mod and i was missing some features on my ATM 8 modpack, like the extended molecular assembler, and another question do you plan on making a faster me pattern? 
Ty for the mod it's so better to play ae2 with this

**Comment by GlodBlock** [comment]
> update the 1.19.2 

saidly no
> a faster me pattern

make larger pattern like 64x dust -> 64x ingot instead of 1x dust -> 1x ingot
