### ISSUE TITLE
Applied Flux - Would like FE findable in JEI for ME Interface and other filters

### ISSUE THREAD

**Issue by chrhyman** [GlodBlock/ExtendedAE#230]
### Version
The modpack I play is running version `1.20-1.1.8-forge` for AppliedFlux. If another version fixes this issue, please let me know so I can tell the modpack maintainers.

### Context
Typically when I create a subnet in AE2, I use an ME interface connected to a storage bus, and configure the interface to supply items/fluids/etc for the subnet to pull from via the storage bus.

In my example, my subnet is filled with tons of ME Interfaces stocking Phytogenic Insolators, and the interfaces have induction cards to power the phytos with network storage FE. The ME Interface for the subnet can easily pull water and phyto-grow from my primary storage, but I was stumped on how to do the same for FE. All three are stored in AE2 cells, so I thought they should be similarly accessible to the interface.

### Where I got stuck
I was not _easily_ able to find FE in JEI by any normal searching. The tooltip implies the mod for the energy called "FE" is "Forge" which was odd to me, but I tried: `@Applied`, `FE`, `Forge`, `@Forge`, `energy`, `flux`. I wasn't able to find it this way.

### How I got unstuck

* Open a terminal where energy is already stored in Applied Flux cells
* Hover over the energy to see "FE" with the implied mod source "Forge"
* Press "A" (default keybind for JEI Add/Remove Bookmark)
* Drag the icon from JEI bookmarks into the ME Interface as usual
* Subnet seems happy!

### Screenshot

I noticed it has a type interface-sounding name: `Wrapped Generic Stack` (and I can't find it in JEI by searching that name, either)

![appflux-jei](https://github.com/user-attachments/assets/4ebf3cd8-a2d0-487f-8b4d-e4d675b1a265)

### Suggestion

If this is still the current behavior (and I'm in the right place!! 😅), I'd suggest that the energy "fluid" be findable in JEI for this filtering purpose if nothing else.

If I can make a bolder suggestion, rather than calling it `FE` from `@Forge`, I'd suggest calling the stack `Forge Energy (FE)` and keeping the mod `@AppliedFlux` which was my expectation, since that energy is only visible due to storage from this mod.

### Thank you!

**Comment by GlodBlock** [comment]
![image](https://github.com/user-attachments/assets/e7546540-e5bf-4cff-a54d-b16ffd52fc19)
you can right click with anything that contains energy to mark FE

**Comment by chrhyman** [comment]
Ah, good to know there's an intended way to get the energy filter. I didn't figure out that method, and my habits had me trying to find it the usual way. Glad that bookmarking in JEI works, though, so going forward I'll probably just use that.
