### ISSUE TITLE
Extended inscriber have a high rendering cost

### ISSUE THREAD

**Issue by Mecr0mage** [GlodBlock/ExtendedAE#231]
While i was setting up an expanded inscribed stack for my base so I could craft some MEGA storage components faster, I noticed after about 512 extended inscribers in my FOV, my frames were starting to take a very noticeable dip so I had to pull back on how many I was planning to have. just to make sure this is not something the base inscribed has an issue with put down 2056 regular inscribers which had no effect on my frames. 
![Screenshot_9](https://github.com/user-attachments/assets/d22e791a-f5ed-4693-8e19-4b9a9fe371ed)
![Screenshot_8](https://github.com/user-attachments/assets/617028ed-3d72-46c3-b379-4910ce1d1efc)

**Comment by Mecr0mage** [comment]
this is on an older version in 1.20 so if this is not an issue in the latest version in 1.21, my apologies.

**Comment by GlodBlock** [comment]
you can turn off the item render of extended inscriber in config.
![image](https://github.com/user-attachments/assets/d51ba8a2-d7f6-4e5a-8aa9-1ed9b624e374)
