### ISSUE TITLE
Oversized Interface's fluid storage capacity can be abused to store fluids in the network

### ISSUE THREAD

**Issue by MageInBlack** [GlodBlock/ExtendedAE#233]
I've checked the oversized interface recently and found out that it can stock up to INT_MAX of millibuckets per slot. It is around 2 million buckets and can be compared to 256k fluid cell with 1 type of fluid. Having 36 slots oversized interface can replace 36 256k fluid cells. it also twice as big for types than a regular fluid cell (18 types).

It is when you put a storage bus onto an oversized interface with fluid in it. Making something like interface autostocking from ae2 guide but not crafting and just holding.

I assumed by x16 times per slot meant i could store about 64 buckets of any fluid per slot. But this insane capacity actually makes them beyond unbalanced to have such fluid storage for _so cheap_.

Update:
Apparently you can overstock it so it accepts **even more** fluid
![image](https://github.com/user-attachments/assets/3f5e36e3-57f2-48f0-bc6c-ac8fab2c6db4)

Update 3: It seems the oversize_interface_multiplier config doesn't apply well for fluids

Update 5: After looking at the code it must throw around this part and then return MAX_LONG that's why it can store up to MAX_LONG in a single slot
https://github.com/GlodBlock/ExtendedAE/blob/0b48a8ccb70292346126931a2c47624c52f49258/src/main/java/com/glodblock/github/extendedae/common/tileentities/TileOversizeInterface.java#L58

**Comment by GlodBlock** [comment]
fixed
