### ISSUE TITLE
App Flux and AE2 heavy lag

### ISSUE THREAD

**Issue by MasiTheCrow** [GlodBlock/ExtendedAE#235]
We are seeing a lot of lag being caused by Applied Flux and AE2 on our server, but we are having issues isolating the problem. Is there a tool to lagbust?

**Comment by MasiTheCrow** [comment]
If you would like to see the spark profile, DM me

**Comment by Lemonjuce13** [comment]
I am a player on this server. Together with staff we have specified the issue to be related to the `distribute()`- function called
[here](https://github.com/GlodBlock/ExtendedAE/blob/appflux/1.20.1-forge/src/main/java/com/glodblock/github/appflux/common/me/service/EnergyDistributeService.java).

In our context its a extended Interface having its faces connected to 4 adjacent modded machines. The function loops over each of the connected nodes on each tick, we think this is what is causing the lag.

**Comment by GlodBlock** [comment]
it has been solved in 1.21
