### ISSUE TITLE
Canner can store ludicrous amount of fluid

### ISSUE THREAD

**Issue by MageInBlack** [GlodBlock/ExtendedAE#237]
According to gui, canner is able to store 2.14MB of fluid, but in truth it is able to store a lot more, probably another LONG_MAX. Also accessible via storage bus.
I assume it is not intended for it to store that much
![image](https://github.com/user-attachments/assets/61f2de47-2fcc-4ddf-9d05-be12aafc57b3)
![image](https://github.com/user-attachments/assets/2a13a96a-1dde-4b04-95c8-7715d594abc1)

**Comment by GlodBlock** [comment]
its capacity is same as normal interface slot's now.
