### ISSUE TITLE
Canner deletes buckets/other containers in fill mode

### ISSUE THREAD

**Issue by MageInBlack** [GlodBlock/ExtendedAE#238]
When I'm trying to fill a bucket in the canner if i have enough for 2 or more buckets/enough to fill a tank and more, it deletes buckets/tanks upon filling them.

How to reproduce:
Fill a canner with 2 or more buckets of fluid. Put a bucket inside. Power it.

**Comment by TheSadKem** [comment]
for me it deleted even with 1 bucket

**Comment by GlodBlock** [comment]
fixed
