### ISSUE TITLE
[MC 1.21.1 Neoforge] Recipes for crystal assembler do not show in JEI

### ISSUE THREAD

**Issue by Saereth** [GlodBlock/ExtendedAE#239]
MC 1.21.1
Neoforge: 21.2.27
JEI: jei-1.21.1-neoforge-19.14.1.141
ExtendedAE: ExtendedAE-1.21-2.0.2-neoforge

The items show in JEi but if you try to check the recipes they dont show any recipes that are crfted in the crystal assembler

**Comment by GlodBlock** [comment]
jei isn't supported since 1.20.4, please use emi.
