### ISSUE TITLE
The Me Wireless Connector built-in GUI fails to render the Mekanism pipeline and causes the game to crash

### ISSUE THREAD

**Issue by yuyeling123** [GlodBlock/ExtendedAE#24]
![Snipaste_2023-11-22_21-21-19](https://github.com/GlodBlock/ExtendedAE/assets/144537390/9cec5fb7-bccf-413a-83b9-85581156a637)
As shown in the figure, when a mekanism pipeline appears in the render range of one me wireless connector, if you try to open the GUI of another matching me wireless connector will cause the game to crash

**Comment by GlodBlock** [comment]
any crash log?

**Comment by yuyeling123** [comment]
[crash-2023-11-22_21.14.39-client.txt](https://github.com/GlodBlock/ExtendedAE/files/13440366/crash-2023-11-22_21.14.39-client.txt)

**Comment by GlodBlock** [comment]
fixed https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-0.1.25-forge
