### ISSUE TITLE
Matrix assembler causes intense lag when requesting big Auto-crafts

### ISSUE THREAD

**Issue by TheSadKem** [GlodBlock/ExtendedAE#241]
ExtendedAE 1.21-2.0.2-neoforge
How to reproduce:
1. make any crafting table pattern
2. put it in a assembler matrix [i have a max size so i dont know if this would cause lag on smaller assembler matrices]
3. have a quite fast cpu [i got 176 co-processors] 
4. request large amounts of it [in this case i would do 10k oak planks]
5. tps goes down to 10 [this is how low the tps would go for me so idk how low it would go for other people]

**Comment by GlodBlock** [comment]
do you have crafting tweaker installed? it will cause lag with matrix assembler.

**Comment by TheSadKem** [comment]
yea it the modpack has crafting tweaks
does it have a config i can disable for the lag to stop?

**Comment by GlodBlock** [comment]
it should be fixed now
