### ISSUE TITLE
Crash when opening ME Wireless Connector

### ISSUE THREAD

**Issue by westriel** [GlodBlock/ExtendedAE#248]
I get a crash (report can be found at [this pastebin](https://pastebin.com/EPYt8wuM)) when attempting to open the receiving end of a ME Wireless Connector. I have one end attached directly to my Controller with a wire next to it (for terminals) separated by a cable anchor + cable facade. I can open the wireless connector that is attached to the Controller just fine, however the remote controller will cause this crash.

This interestingly does not impede the function of the device as channels and devices connected are connected to the rest of the system and are reachable from base terminals.

**Comment by GlodBlock** [comment]
fixed
