### ISSUE TITLE
Bug: export bus is offline after upgrade

### ISSUE THREAD

**Issue by Mithi83** [GlodBlock/ExtendedAE#255]
In my ATM10 world I had a ME Export Bus (from AE2 itself) in a network and it was online. Then I applied a Import/Export Bus Upgrade from ExtendedAE. The upgrade itself worked, but the resulting ME Extended Export Bus was offline even though the ME Export Bus was previously online. I had to break and place it back down to bring it online, losing my settings because I did not save them on a memory card. I later get the idea to try to remove and replace a cable to bring the ME Extended Export Bus online after the upgrade. 

I'd expect the ME Extended Export Bus to be brought online automatically during the upgrade process. This probably also affects other kinds of upgrades ExtendedAE provides.

MC 1.21.1, NeoForge 21.1.54, AE2 19.0.23, ExtendedAE 1.21-2.0.4

**Comment by Kami-prog** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by GlodBlock** [comment]
fixed

**Comment by OldieFox** [comment]
Can this fix be ported to Fabric 1.20.1?
