### ISSUE TITLE
[1.21.1] Kubejs Added Infinity Cell's Tooltips Crash the Client

### ISSUE THREAD

**Issue by Drackion** [GlodBlock/ExtendedAE#260]
Mod Version: 2.1.0-Neoforge
Lib Version: 2.0-Neoforge
Pack: ATM 10 0.62

Expected Behaviour:
To render the tooltips on Infinity Cells added via KJS without the client crashing.

Actual Behaviour:
Hovering over Infinity Cells added via KJS or searching in creative search crashes the client.

Logs:
https://mclo.gs/A44xcZo

**Comment by Drackion** [comment]
I have also discovered this issue also breaks Forbidden Arcanus's JEI Integration

**Comment by GlodBlock** [comment]
this is because 'minecraft:moss' isn't a valid item id
https://github.com/AllTheMods/ATM-10/blob/main/kubejs/startup_scripts/ExtendedAE/InfinityCells.js#L23
i think it should be 'minecraft:moss_block'
it isn't extendedae's issue

**Comment by Drackion** [comment]
ok thx
