### ISSUE TITLE
assembler matrix

### ISSUE THREAD

**Issue by M0xiito** [GlodBlock/ExtendedAE#267]
where can I change the number and size of the matrix assembler?

**Comment by GlodBlock** [comment]
it is hardcoded now, so you can't change it

**Comment by M0xiito** [comment]
it is so very weak, a maximum of 1k items are created per tick

**Comment by GlodBlock** [comment]
it can be changed in config now

**Comment by M0xiito** [comment]
there is a new problem after running several crafts at the same time, the system breaks down and more than one crafting does not start anymore

**Comment by M0xiito** [comment]
![image](https://github.com/user-attachments/assets/8f61ee41-073e-42b5-9d19-88009dddc639)

**Comment by M0xiito** [comment]
She doesn't do two crafts at once

**Comment by M0xiito** [comment]
![image](https://github.com/user-attachments/assets/1f24977c-6adb-48dd-8d5f-a9f69d8fcfe2)
![image](https://github.com/user-attachments/assets/1e54b709-064f-412a-a4b8-f86c92f3d3d1)
