### ISSUE TITLE
Reaction Chamber not working when X amount of acceleration cards installed

### ISSUE THREAD

**Issue by AngelOfTheNight** [GlodBlock/ExtendedAE#268]
As the title says If I go to either auto craft or regular craft a recipe

A few of the ones I have run into so far:

Example with making Charged Certus

In Reaction Chamber with 4 acceleration cards - Not working
![image](https://github.com/user-attachments/assets/21675438-1071-4370-bc63-00e8be435370) 

With 3 acceleration cards - Not working
![image](https://github.com/user-attachments/assets/426c5db9-7ea9-4277-abeb-df5d823870ee)

With 2 acceleration cards - Not working
![image](https://github.com/user-attachments/assets/d85bb1f3-003a-4bc5-9489-85310197fd0e)

With 1 acceleration cards - Working
![image](https://github.com/user-attachments/assets/bab5f8ef-4205-4935-81a1-3af6694c7f76)

Example with Matter Ball -> Singularity with 4 cards - Not Working
![image](https://github.com/user-attachments/assets/0bf21af9-98a4-4cc0-afe8-4b1b119d76fc)

Works with only one card as well 
![image](https://github.com/user-attachments/assets/e7b92983-d901-4990-a0e4-351132386f32)

Example to make Entro Crystal
4 cards - Not Working
![image](https://github.com/user-attachments/assets/129026c7-de5e-4bde-bf22-5859643226fc)

3 Cards - Works (The crafting had already exported but it worked)
![image](https://github.com/user-attachments/assets/e01a9c41-055b-4f46-a8df-0f30c3ec7225)

A crash log dump after trying to craft just in case this is helpful
[Minecraft ATM10 ExtendedAE Error.txt](https://github.com/user-attachments/files/17352699/Minecraft.ATM10.ExtendedAE.Error.txt)

**Comment by GlodBlock** [comment]
Reaction Chamber is from AdvancedAE, not ExtendedAE.
https://github.com/pedroksl/AdvancedAE

**Comment by AngelOfTheNight** [comment]
Sorry, was looking at the Crystal Assembler before :)
