### ISSUE TITLE
Assembler Matrix hangs with patterns with substitutions enabled.

### ISSUE THREAD

**Issue by Yariazen** [GlodBlock/ExtendedAE#269]
I haven't tested it outside of atm10, but the Assembler Matrix doesn't like substitutions enabled.

![image](https://github.com/user-attachments/assets/98083669-108c-494e-a749-6f6e9fb4f31b)
![image](https://github.com/user-attachments/assets/4bd6c4c6-e5fc-43d9-9925-346654e3c5de)

**Comment by GlodBlock** [comment]
i can't reproduce this

https://github.com/user-attachments/assets/ab4a1955-701e-4c04-9dac-c5cc2a2db63d

**Comment by Yariazen** [comment]
Apologies, I can't replicate it either since updating ATM10. With that being the case, it could've been caused by any number of things so I'll go ahead and close this for lack of reproducibility. Thanks for looking into it!
