### ISSUE TITLE
[Suggestion] Update ME Extended Drive model to have 20 slots instead of 10

### ISSUE THREAD

**Issue by taj1994** [GlodBlock/ExtendedAE#27]
Having twice as many storage cells in the same amount of space is really nice, but you can only see the status of the first ten cells without going into the drive's interface. This could be an issue when trying to figure out how close to full a larger system is, or how many partially full drives you have

Loving the mod overall since I discovered it a couple weeks ago though. Good job!

**Comment by GlodBlock** [comment]
its model actually displays 20 slots
![22](https://github.com/GlodBlock/ExtendedAE/assets/60341015/e383571a-3dbb-4619-8afa-db71bef4ab5b)
but yeah it is hard to see the last 10 slots, i will change that later
