### ISSUE TITLE
Memory card doesnt copy (or paste) tag filter rule between tag export buses

### ISSUE THREAD

**Issue by akasaka-kun** [GlodBlock/ExtendedAE#270]
Describe the bug
the memory card doesnt copy (or paste) tag filter rule between tag export buses when copying settings

Which minecraft version are you using?
1.20.1

On which mod loaders does it happen?
Forge

Crash log (forced crash for extra info)
https://bytebin.lucko.me/BTcUJXjgAS

**Comment by GlodBlock** [comment]
fixed
