### ISSUE TITLE
I don‘t see recipes in jei 

### ISSUE THREAD

**Issue by zuken1997** [GlodBlock/ExtendedAE#274]
I want to Build Extended ae stuff but JEI  don’t Show recipes… 
Version: ExtendedAE-1.21-2.1.1-neoforge.jar
               Jei-1.21.1-neoforge-19.21.0.246.jar
               Glodium-1.21-2.2-neoforge.jar

**Comment by Comstock112** [comment]
Same

**Comment by GlodBlock** [comment]
extendedae doesn't support jei. you need to add jei extra if you want to use jei. https://www.curseforge.com/minecraft/mc-mods/ftb-jei-extras

**Comment by zuken1997** [comment]
Ok thx but can you Write this in the Description on curseforge pls :)

**Comment by GlodBlock** [comment]
sure
