### ISSUE TITLE
在服务器使用AE2 Network Analyser检查网络时连接丢失

### ISSUE THREAD

**Issue by FBF23** [GlodBlock/ExtendedAE#278]
![1](https://github.com/user-attachments/assets/55e9da4b-3bdb-4492-90b2-f35d9592fff9)

### 报告：[disconnect-2024-10-27_17.26.17-client.txt](https://github.com/user-attachments/files/17542314/disconnect-2024-10-27_17.26.17-client.txt)
接入致密线缆也会触发

**Comment by GlodBlock** [comment]
能提供一下latest.log吗

**Comment by FBF23** [comment]
> 能提供一下latest.log吗
[latest.log](https://github.com/user-attachments/files/17555519/latest.log)
触发问题后会应为手持工具无法重新进入服务器，只能把手持的工具删掉才能进入

**Comment by FBF23** [comment]
> 能提供一下latest.log吗

[latest.log](https://github.com/user-attachments/files/17555543/latest.log)
触发问题后会因为手持工具无法进入，只能工具移除才能进

**Comment by GlodBlock** [comment]
修了
