### ISSUE TITLE
mod冲突

### ISSUE THREAD

**Issue by TheDesiringOne** [GlodBlock/ExtendedAE#280]
Starlight1.1.2和ExtendedAE-1.20-1.2.0-forge有冲突：在使用g键查看ExtendedAE相关物品教程时，会导致游戏崩溃。ae2原版物品则不会。

**Comment by GlodBlock** [comment]
加这个mod https://www.curseforge.com/minecraft/mc-mods/starlightxae

**Comment by TheDesiringOne** [comment]
ok，谢谢。
