### ISSUE TITLE
ME无限圆石元件过早创建AEItemKey，导致与修改物品默认组件的模组不兼容

### ISSUE THREAD

**Issue by Phoupraw** [GlodBlock/ExtendedAE#286]
我有一个模组将所有物品的最大堆叠数量乘1.5（不是mixin，而是neoforge提供的事件），但是`AEItemKey`在创建时会缓存所有组件的散列码以及最大堆叠数量，而ME无限元件在物品注册时就会创建`AEItemKey`，此时修改默认组件的事件还没有运行，等到运行完毕后ME无限元件内的`AEItemKey`与之后创建的`AEItemKey`不同（两者序列化后完全相同），导致输出总线无法提取圆石。

MC 1.21.1
ExtendedAE 1.21-2.1.2-neoforge

**Comment by GlodBlock** [comment]
那是什么mod

**Comment by Phoupraw** [comment]
是我自己写的模组😏没有发布。fabric模组，用信雅互联在neoforge上运行。

**Comment by GlodBlock** [comment]
修了
