### ISSUE TITLE
[Suggestion] Wireless Connect support ae2 color applicator to change color

### ISSUE THREAD

**Issue by DancingSnow0517** [GlodBlock/ExtendedAE#29]
![image](https://github.com/GlodBlock/ExtendedAE/assets/60736156/ce66385b-4bf6-4e75-ba69-612bc3295814)
Modify the color of the center box, similar to GTNH

**Comment by GlodBlock** [comment]
added https://github.com/GlodBlock/ExtendedAE/commit/b90913398d206abb3f2c2c20826631e5c7a182af
