### ISSUE TITLE
ME Storage Bus does not transfer FE energy to machines (AppliedFlux Add-on)

### ISSUE THREAD

**Issue by IL0co** [GlodBlock/ExtendedAE#295]
## Describe the Bug
Energy continuously flows into the ME system via the ME Flux Bus, but it does not transfer to connected machines through the ME Storage Bus or store in the energy cell (Powah mod). I added `FE` to the whitelist in the ME Storage Bus and also tried using an Inverter Card, but the result was the same—the energy did not transfer.

I also attempted to create a subnet where the ME Interface was fully filled with `FE`, and the other end was connected to a machine (only 2 components in the network), but the energy still did not transfer.

## How to Reproduce the Bug
1. Build a basic ME network that includes a disk drive, an `FE` energy storage cell, an ME Controller (powered separately), and an access terminal.
2. Connect a constant energy source (not a creative cell; you need energy to flow continuously into the network) to the ME system via an ME Flux Bus.
3. Place any machine (e.g., an electric furnace) and connect an ME Storage Bus to it. In the ME Storage Bus settings, add an Inverter Card or add `FE` to the whitelist, and set its priority to +1.
4. Observe that the energy does not transfer to the machine.

## Expected Behavior
The ME Storage Bus is expected to transfer `FE` energy to the connected machine, acting similarly to the ME Flux Bus, allowing the machine to receive power and operate.

## Additional details
Modpack ATM - 10 v1.25

## Dump (hold F3 + C 10 seconds)
https://gist.github.com/IL0co/d57dada67220dd277f52fd43de75890f

**Comment by GlodBlock** [comment]
do you have the screenshot of your setup? it should with my setup..

https://github.com/user-attachments/assets/a62149d7-3216-47a1-b3c3-cb203e4653b6

**Comment by IL0co** [comment]
In the main network everything works as it should, my mistake that I did not check it in it.
But the problem is that in the subnet, if we transfer the inventory of the ME network via the ME Interface to the ME Storage Bus of the second network, then the ME Storage Bus, which is configured to store energy, simply does not work, but the ME Export Bus works, which means that there is energy in this network in fact.

https://github.com/user-attachments/assets/52e3bd4e-40f3-41a4-bfd0-6eb7ce14b2f6

**Comment by GlodBlock** [comment]
You made a mistake: the storage bus in AE can't input or output anything(item, fluid, energy or whatever), it **stores** stuff. The interface in main network can't push energy to the storage bus because it has been **stored**, so the export bus can output energy.
Your setup is equivalent to use a pipe to pump water through storage bus, and hope the water is stored in ME network. Of course it won't work.
The correct setup is replace the storage bus with another interface.

**Comment by IL0co** [comment]
Yes, you are right, I was mistaken about this mechanic (default from AE2) with ME Storage Bus and thought that it can transfer items from static storage, suggestion #287 would help me in this case, sorry for bothering me.
