### ISSUE TITLE
fabir1.20.1 Crash occurred after adding

### ISSUE THREAD

**Issue by iltworld** [GlodBlock/ExtendedAE#30]
MODS only has AE2 and ExtendedAE, but once ExtendedAE is added, the game will crash upon startup
[崩溃日志.txt](https://github.com/GlodBlock/ExtendedAE/files/13600599/default.txt)

**Comment by GlodBlock** [comment]
已修复https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-0.1.1-fabric

**Comment by iltworld** [comment]
> 已修复 https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-0.1.1-fabric

感谢
