### ISSUE TITLE
Tag Export Bus doesn't recognize custom tags from KubeJS

### ISSUE THREAD

**Issue by TheLarkInn** [GlodBlock/ExtendedAE#304]
It appears that custom tags that I've added via KubeJS:

```js
  ServerEvents.tags("item", (event) => {
    event.add(`kubejs:ekof_processable_${rpm}`, itemName);
  });
```

Doesn't get recognized when referencing it inside of the Tag Export Bus: 

![image](https://github.com/user-attachments/assets/99e93037-b3af-44b5-a533-b8ed44645020)
![image](https://github.com/user-attachments/assets/9d6a5bef-21cc-4204-8b4d-232c275f8fbe)

Am open to contributing a fix if possible.

**Comment by GlodBlock** [comment]
it won't work when hot reload tags, if you restart game it should work.
it has been fixed anyway
