### ISSUE TITLE
Pattern modifier doesn't work to multiply amounts in patterns

### ISSUE THREAD

**Issue by ghost** [GlodBlock/ExtendedAE#310]
See https://github.com/AllTheMods/ATM-10/issues/802
Reproduced by me:
https://github.com/user-attachments/assets/ef8818c4-7e5b-4bb2-b21e-b629d1bc4ed2
EAE version was 1.21-2.1.6-neoforge

**Comment by pedroksl** [comment]
I came in here because I thought it could be my fault since I mixin the pattern modifier. However, you're trying to modify a crafting pattern. Those can't be modified, only processing patterns.

**Comment by ghost** [comment]
Well that's what i get for trying to report on issues in features i never use myself i suppose. Dont even know what the thing is supposed to do when its working correctly xD
