### ISSUE TITLE
[Bug] Pattern Provider Upgrade Fails to Upgrade Plane-like Pattern Providers.

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/ExtendedAE#35]
Pattern Provider Upgrade cannot upgrade plane-like pattern providers, while it works fine with the block form.

In the latest version for mc 1.19.2

**Comment by GlodBlock** [comment]
you need to click the front face of pattern provider, sides won't work

**Comment by YiRanMushroom** [comment]
Okey, but when clicking sides of the provider, it consumes the upgrade and does nothing, so I still think it should be considered a bug. BTW are you still maintaining the version for minecraft 1.19.2?

**Comment by GlodBlock** [comment]
ok i will fix it soon. i still fix bugs in 1.19 but won't add new features to it

**Comment by GlodBlock** [comment]
fixed https://github.com/GlodBlock/ExtendedAE/releases/tag/1.19-0.2.1-forge
