### ISSUE TITLE
server won't stop - Fabric

### ISSUE THREAD

**Issue by rutizar22** [GlodBlock/ExtendedAE#36]
Hi.  Tried installing this addon on versions 1.20.1 and 1.19.2. The server does not stop completely. It stops at the message and does not shut down completel: 
**[Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved.**

Log file attachment.

[latest.log](https://github.com/GlodBlock/ExtendedAE/files/13828981/latest.log)

**Comment by GlodBlock** [comment]
well it is casued by [configuration](https://www.curseforge.com/minecraft/mc-mods/configuration) and extendedae is using that mod as config lib.
you can report this issue to that mod's repo, if the author doesn't want to fix and i will replace config lib with the other.

**Comment by rutizar22** [comment]
Thank you. I informed him. When I hear back from him, I'll get back to you.

**Comment by rutizar22** [comment]
Hi. He sayd me:
1.19 versions have been fixed

[1.19.2](https://www.curseforge.com/minecraft/mc-mods/configuration/files/5009543)
[1.19.4](https://www.curseforge.com/minecraft/mc-mods/configuration/files/5009502)
Also there is no Fabric version for 1.20.1, at least not official one

**Comment by GlodBlock** [comment]
don't worry about 1.20 one. i will push an update soon

**Comment by rutizar22** [comment]
ty, i'm wait

**Comment by GlodBlock** [comment]
check the latest fabric branch release

**Comment by rutizar22** [comment]
thank you. it works
