### ISSUE TITLE
Massiv FPS loss while looking at Extended Inscribers.

### ISSUE THREAD

**Issue by LuziferSenpai** [GlodBlock/ExtendedAE#37]
Hey,

so when I'm looking at 128 Extended Inscribers I lose over 70 FPS.
It gets even worse the more I add, how can this be?
They are not even running.

My Frames are capped at 200, it gets even worse with Unlimited FPS.

From 500 down to 100 - 110.

From my testing it has something todo with the rendering of the items inside, as soon as I put the presses into it, it gets worse and worse.

![javaw_HvZCOJu4wj](https://github.com/GlodBlock/ExtendedAE/assets/38015859/f8f4fa47-1235-4564-b35e-56523ea522a6)
![javaw_Vni80GPion](https://github.com/GlodBlock/ExtendedAE/assets/38015859/88776ad8-ce40-422a-ae01-fcac0c86a82d)

**Comment by GlodBlock** [comment]
i'm not good at rendering stuff so i can't promise it can be improved in future, but i will try

**Comment by LuziferSenpai** [comment]
Wouldnt it be then a solution to add a option to disable item rendering?

Or have a option for a full block where you dont even render anything inside.

**Comment by GlodBlock** [comment]
yeah that is also a good idea

**Comment by GlodBlock** [comment]
you can disable the item render in config now
https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-1.0.1-forge
