### ISSUE TITLE
How do you use the Extended Export Bus?

### ISSUE THREAD

**Issue by Burkino** [GlodBlock/ExtendedAE#38]
I'm trying to export all mystical agriculture essences to storage drawers. I have tried `mysticalagriculture:essences` and `mysticalagriculture:*_essence` but neither seem to work.

![image](https://github.com/GlodBlock/ExtendedAE/assets/24849979/283b36cf-ad0a-4e04-a783-46f4151c97a3)

**Comment by GlodBlock** [comment]
do you use the latest extendedae? the tag bus is bugged in 0.1.29
