### ISSUE TITLE
Can I add a network visualization tool?

### ISSUE THREAD

**Issue by tangzixiang-hash** [GlodBlock/ExtendedAE#39]
https://github.com/bdew-minecraft/ae2stuff
I like this tool very much in gtnh, but I haven't seen it in the higher version, when I was playing atm9, I was troubled by expanding my ae network, I always couldn't tell where the P2P connection was, I urgently needed this tool, could I make a this, add it to this mod, thank you very much, if I can I would like to sponsor you 10 dollars, this is my pocket money this month, I am in China, in high school, there is no more.

**Comment by GlodBlock** [comment]
这个工具我准备放进别的mod里，还有我不收赞助

**Comment by tangzixiang-hash** [comment]
Thank you very much, is this mod out, I like this feature very much.

**Comment by tangzixiang-hash** [comment]
呀，原来是大佬啊，我以为是外国友人。

**Comment by tangzixiang-hash** [comment]
大佬，谢谢你的mod。

**Comment by tangzixiang-hash** [comment]
大佬，请问下，这个mod1月会做出来吗。

**Comment by GlodBlock** [comment]
看情况

**Comment by GlodBlock** [comment]
在这里 https://legacy.curseforge.com/minecraft/mc-mods/ae2-network-analyser
