### ISSUE TITLE
New QoL tricks

### ISSUE THREAD

**Issue by monochromem1nd** [GlodBlock/ExtendedAE#4]
what about a wireless connector (like ae2 stuff) +/ newer cables with more bandwidth? (yes i know i can set channel mode but its too casual)

**Comment by GlodBlock** [comment]
> wireless connector   

use ae2additions' wireless connecter

> cables with more bandwidth

well that isn't easy to implement so i can't promise it

**Comment by monochromem1nd** [comment]
casual mechanic in ae2adittions))

**Comment by monochromem1nd** [comment]
> well that isn't easy to implement so i can't promise it

ye i know n understand

**Comment by GlodBlock** [comment]
the wireless connector is added now https://github.com/GlodBlock/ExtendedAE/releases/tag/1.19-0.1.1-fabric
the cable is beyond my ability

**Comment by monochromem1nd** [comment]
nice work!

**Comment by monochromem1nd** [comment]
@GlodBlock I think u forgot some commit, for in trying to refactor current code, found a bug that is not in the production version. (for 2 wireless connector to work, it must be powered) (this is not in the production version).

**Comment by GlodBlock** [comment]
yea i forgot that lol
