### ISSUE TITLE
[Suggestion] Add a Threshhold Level Emitter

### ISSUE THREAD

**Issue by LuziferSenpai** [GlodBlock/ExtendedAE#40]
Hey,

it would be awesome to get a Level Emitter that emits a redstone signal when below/above one point and then disables/enables this signal again when another point is reached.

So like the Treshhold Switches from Create.

**Comment by GlodBlock** [comment]
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/ca6ca3a0-b0a6-43e8-8330-8f23dc0ebcc0)
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/b8671b07-4d5c-48f2-8aaf-3574c5e48925)
ae's level emitter alrready can send redstone signal

**Comment by LuziferSenpai** [comment]
I want something like this from create.
![javaw_E6uV1DTxrF](https://github.com/GlodBlock/ExtendedAE/assets/38015859/9acea2b7-fc3f-44ec-997f-c43dab9b29d0)

Enable at when the lower OR upper point is reached, disable when the other point is reached.

**Comment by GlodBlock** [comment]
i see

**Comment by GlodBlock** [comment]
added https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-1.0.2-forge
