### ISSUE TITLE
Adding Improved molecular for 1.12.2 version PLEAS!!

### ISSUE THREAD

**Issue by Artiks54** [GlodBlock/ExtendedAE#43]
1)Adding Improved molecular for 1.12.2 version PLEAS!!
2)Adding  improved co-processor for 1.18-1.20

**Comment by GlodBlock** [comment]
> 1)Adding Improved molecular for 1.12.2 version PLEAS!! 2)Adding improved co-processor for 1.18-1.20

use lazyae2's molecular assembler



> 2)Adding improved co-processor for 1.18-1.20

use mega co-processor from MEGA
