### ISSUE TITLE
[Suggestion]add FE energy cells like mana cells.

### ISSUE THREAD

**Issue by zhcn000000** [GlodBlock/ExtendedAE#47]
add FE energy cells like mana cells [Applied Botanics] so that we can use the network to transfer energy, supply energy to the network itself or to supply energy the machine through interface.

**Comment by zhcn000000** [comment]
Also view, charge and discharge in the terminal.

**Comment by GlodBlock** [comment]
我知道，你先别急

**Comment by CN0001** [comment]
你发的信件我已经收到（张继炎）

**Comment by GlodBlock** [comment]
在这里https://legacy.curseforge.com/minecraft/mc-mods/applied-flux

**Comment by yuyeling123** [comment]
> 在这里 https://legacy.curseforge.com/minecraft/mc-mods/applied-flux

我想问一下是否可以让ae additions的supper storage call和applied flux一样显示存储的电量
![image](https://github.com/GlodBlock/ExtendedAE/assets/144537390/d2663537-1a67-4061-a990-9e74cf5da802)

**Comment by GlodBlock** [comment]
这个你得找aeaddition的作者，我这里弄不了

**Comment by yuyeling123** [comment]
好的，谢谢

**Comment by zhcn000000** [comment]
非常感谢制作这个模组，可以再添加几个功能吗，抱歉英语不好，没法用英语描述清楚
1，让fe元件存储的电量可以供应本ae网络，或添加一个方块以做到这个，这样就不用接出一个导线绕一圈回来了
2，给me输入，输出，存储总线还有样板终端添加标记能量的功能，这样就不用使用集成动力的集成合成学标记能量控制自动化合成了
3，让终端中充电绕过物品充能速度上限或长按充能，直接在网络内对着像通用机械meka装备这样有充能速度上限的装备在终端要一直用鼠标点才能充满能量，有点费鼠标
4，便携元件（可以当电池用）和创造元件

**Comment by GlodBlock** [comment]
> 1，让fe元件存储的电量可以供应本ae网络，或添加一个方块以做到这个，这样就不用接出一个导线绕一圈回来了

这个会带来性能问题，而且ae也没开放相应的api

> 2，给me输入，输出，存储总线还有样板终端添加标记能量的功能，这样就不用使用集成动力的集成合成学标记能量控制自动化合成了

已经实现了

> 3，让终端中充电绕过物品充能速度上限或长按充能，直接在网络内对着像通用机械meka装备这样有充能速度上限的装备在终端要一直用鼠标点才能充满能量，有点费鼠标

有空做

> 4，便携元件（可以当电池用）和创造元件

我准备让普通元件可以直接当电池用，另外做个便携意义不大

**Comment by zhcn000000** [comment]
<img width="1280" alt="111" src="https://github.com/GlodBlock/ExtendedAE/assets/52312319/136121fc-fbb7-4b82-91dd-8c7b381c4a45">
<img width="1280" alt="111" src="https://github.com/GlodBlock/ExtendedAE/assets/52312319/cd91007b-434f-4f0d-a4db-ebccad0ff600">
好吧,没有注意到存储总线和样版终端已经可以了,所以这个是bug?

**Comment by GlodBlock** [comment]
输入输出总线是特意没做的，用flux accessor

**Comment by zhcn000000** [comment]
要不做个类似于能量io卡的强化让输入输出总线支持能量吧,这样就可以一个输入总线支持供应一台机器的物品,流体,能量了,这样只占一个频道省事
