### ISSUE TITLE
Additional storage bus/exporter documentation

### ISSUE THREAD

**Issue by Mazila9968** [GlodBlock/ExtendedAE#51]
A short hint in the form of an example or an addition to the in-game documentation on how to store/export op tags. I can't find information on this topic. It was not possible to obtain a practical result.

**Comment by GlodBlock** [comment]
first you need to find out the tag of item/fluid you want to filter.
 if you have kjs installed, you can use /kjs hand to see the tags of the item you are holding
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/fcf333aa-eeb0-47e8-97f1-840b39fd441b)
then you input the tag to the input bar(the # doesn't needed) and it is all done
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/0b091d8e-4cf8-43fc-9f6a-117979bb3e7b)

**Comment by elijahward** [comment]
I would like to know how to add multiple tags to export/storage. They must have both Tags to export/storage.

**Comment by GlodBlock** [comment]
> I would like to know how to add multiple tags to export/storage. They must have both Tags to export/storage.

use | to add multiple tags. for example if you want to filter coal(forge:gems/coal) and iron(forge:ingots/iron), you need to input `forge:gems/coal | forge:ingots/iron`.

**Comment by MadSciSlack** [comment]
Please add this info to your mod page!  This is literally the only info on this topic!

Also, some info on the Ingredient Buffer would be really good.  I currently know nothing about this and can't find any information.

**Comment by GlodBlock** [comment]
there is an in-game guide and all info you need is here. click the '?' button to open it
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/8b79b561-1260-4afc-8d33-0882f6357406)
