### ISSUE TITLE
超级超级感谢你。

### ISSUE THREAD

**Issue by tangzixiang-hash** [GlodBlock/ExtendedAE#52]
今天我想看下你还发行了那些mod，发行你把网络分析在1.20中做出来，太感谢你了，你在14号做出来的，可惜我今天才发现。
我在curseforge.com实在没找到哪里可以评论，只能再回到这里了。
总之，谢谢你。

**Comment by tangzixiang-hash** [comment]
![image](https://github.com/GlodBlock/ExtendedAE/assets/60438085/c1006fc4-acfa-433f-ba6e-7ab751bd6512)
![image](https://github.com/GlodBlock/ExtendedAE/assets/60438085/4c1d8210-2896-40b6-894d-f5e36493ba06)
![image](https://github.com/GlodBlock/ExtendedAE/assets/60438085/e4170f6f-6163-4ac2-80cf-e7e8129d7f75)

在游玩过程中我发现节点方块是半透明的，导致亮度偏高和设置颜色不匹配，且AE2的P2P节点显示为白色，无法调节.
除此之外，感觉非常的好。

**Comment by tangzixiang-hash** [comment]
我感觉其实还可以，但是有个开关可以调整透明度开启关闭，或者调整透明度，会更加好一点，非常感谢

**Comment by GlodBlock** [comment]
过几天改

**Comment by GlodBlock** [comment]
还有你是在atm9上用的吗，有没有遇到卡死的问题

**Comment by tangzixiang-hash** [comment]
目前没有遇到卡死的现象，可能是我的规模太小了，我尽力快速发展gt系列，多搞点ae试一下。

**Comment by GlodBlock** [comment]
修了 https://legacy.curseforge.com/minecraft/mc-mods/ae2-network-analyser/files/5052023
