### ISSUE TITLE
新版本效果很好，渲染效果你看这样可以吗。

### ISSUE THREAD

**Issue by tangzixiang-hash** [GlodBlock/ExtendedAE#57]
![image](https://github.com/GlodBlock/ExtendedAE/assets/60438085/fb903c98-8497-45f2-a27e-e31988093b21)
频道的文字渲染，可不可以在节点的上方，
![image](https://github.com/GlodBlock/ExtendedAE/assets/60438085/8f09a58e-f870-4da9-a911-bf459d9081d2)
这样渲染的话，在远距离，文字被遮挡了一半了。

**Comment by monochromem1nd** [comment]
I think it makes sense render text on top of everything

**Comment by GlodBlock** [comment]
修了 https://legacy.curseforge.com/minecraft/mc-mods/ae2-network-analyser/files/5056093
应该是embeddium搞的问题
