### ISSUE TITLE
[Suggestion] Publish the mod on Modrinth

### ISSUE THREAD

**Issue by MageInBlack** [GlodBlock/ExtendedAE#58]
I haven't seen it mentioned in the issues before, so I wanted to ask you to publish this mod on Modrinth. Even though this mod is provided under the LGPL-3.0 because of CurseForge and Modrinth policies sometimes it is not recommended to use mods from both, especially in public modpacks.

Could you provide this mod on Modrinth or is it a CurseForge only mod?

**Comment by GlodBlock** [comment]
i am too lazy to publish mod in multip platforms, but i have allowed the third party download in my curseforge project so you should be able to download it outside curseforge

**Comment by monochromem1nd** [comment]
> i am too lazy to publish mod in multip platforms, but i have allowed the third party download in my curseforge project so you should be able to download it outside curseforge

can be set up to automatically publish by button)

**Comment by GlodBlock** [comment]
:clueless:

**Comment by monochromem1nd** [comment]
kk, I will do it then.

**Comment by monochromem1nd** [comment]
@GlodBlock sent you an invitation to the modrinth

**Comment by monochromem1nd** [comment]
I will try to make it look pretty nice this weekend

**Comment by monochromem1nd** [comment]
https://modrinth.com/mod/extended-ae

@GlodBlock think it may be closed

**Comment by 300f20t** [comment]
I think the Morinth version is very late. I can help with that.

**Comment by FelixKLG** [comment]
@Ftrless Can you also push the supporting Glodium library.

CF:
https://www.curseforge.com/minecraft/mc-mods/glodium

Modrinth:
https://modrinth.com/mod/glodium
Multiple versions behind, causes missing dependency issues when using Modrinth to installed ExtendedAE.

Thx.
