### ISSUE TITLE
[Suggestion] Easy renaming of AE components

### ISSUE THREAD

**Issue by xGenius123** [GlodBlock/ExtendedAE#60]
Hi,

It would be cool if there was a way to rename AE2 components withouit the use of anvils and on the spot. I know in AE2UE and GTNH version of AE you are able to use a cutting knife on a machine to change its name. It also gives a cutting knife a new cool feature other than making anchors, and Inscriber Name Presses (which i think are useless given you can do the same thing with an anvil on the spot)

Example from GTNH:
![](https://i.imgur.com/66mYAOY.png)

**Comment by GlodBlock** [comment]
added https://github.com/GlodBlock/ExtendedAE/releases/tag/1.20-1.0.4-forge
