### ISSUE TITLE
appflux

### ISSUE THREAD

**Issue by gjmhmm8** [GlodBlock/ExtendedAE#63]
建议用ME接口和样板供应器传输能量，而不是通量访问点，兼容MEGA 256M存储组件，提供更大的存储容量

**Comment by gjmhmm8** [comment]
不然的话mek疏导矩阵加通量网络它不香吗

**Comment by GlodBlock** [comment]
接口和供应器已经可以标记能量了，mega等90自己做兼容

**Comment by gjmhmm8** [comment]
怎么操作的，1.20没看到

**Comment by gjmhmm8** [comment]
还不如主动输出能量，输入的话可以考虑从能源接收器或者me控制器输入，同时能源元件可以给ae系统供能

**Comment by gjmhmm8** [comment]
说实在的，256k 1.1t也是够小的了，256m还差不多，隔壁深度物品和深度流体都做到65536k了

**Comment by gjmhmm8** [comment]
<img width="272" alt="Snipaste_2024-01-31_02-30-33" src="https://github.com/GlodBlock/ExtendedAE/assets/73775469/223e21d5-7127-4bdc-b869-66301fab516e">
mek随便搞搞就上p

**Comment by GlodBlock** [comment]
通量访问点输入输出是没有上限的，而且能主动输出

**Comment by gjmhmm8** [comment]
ae2那个输出没上限应该也不难吧，上限设为总容量，me接口和样板供应器主动输出，输入就用ae2自带的那个能量供应器

**Comment by gjmhmm8** [comment]
大不了ctrlcv

**Comment by gjmhmm8** [comment]
同时输入输出的话怕有些线缆出bug

**Comment by GlodBlock** [comment]
接口一直都不能主动输出，供应器只有下单能输出，这些是ae自己的设定我改不了。我给的能量交互就是通量访问点，要是有bug你跟我说

**Comment by gjmhmm8** [comment]
供应器输入，不是输出，接口的话hook不知道行不行，能主动输出能量最好，不然实用性不大

**Comment by gjmhmm8** [comment]
不能的话一条mek的能量管道加一个通量接入点它不香吗

**Comment by gjmhmm8** [comment]
可以的话少接一个面，再加上无限传电还有点优势

**Comment by gjmhmm8** [comment]
原本的改不了extae的也总能改了吧

**Comment by GlodBlock** [comment]
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/570e7a6e-0d60-48ce-9f48-61dc2c5c5512)
这是别人的搭法，接口做输入，接入点做输出

**Comment by gjmhmm8** [comment]
感觉也是够麻烦的，还不如me接口和样板供应器自动输出能量

**Comment by gjmhmm8** [comment]
至少扩展应该是可以改的

**Comment by gjmhmm8** [comment]
等价考不考虑弄个mod做兼容

**Comment by GlodBlock** [comment]
不想这么搞

**Comment by gjmhmm8** [comment]
目前说实在的这模组没啥用，说容量比不过mek疏导矩阵，说方便性比不过通量网络，如果每台机器还要单独接的话我为啥不用通量网络，还不用受频道限制
<img width="778" alt="Snipaste_2024-01-31_11-34-23" src="https://github.com/GlodBlock/ExtendedAE/assets/73775469/3988bd5e-f819-4c8f-8cfa-15a9297c6eb4">

**Comment by gjmhmm8** [comment]
<img width="335" alt="Snipaste_2024-01-31_11-38-17" src="https://github.com/GlodBlock/ExtendedAE/assets/73775469/49d83a55-64f0-4f53-9a74-1ca44c63bf1b">
这设计是不是有点问题，磁盘一满就把接口全堵住了

**Comment by GlodBlock** [comment]
那肯定会堵的，本质上能量和物品流体都是一样的，你要是物品磁盘满了还继续塞物品进去也会堵住

**Comment by gjmhmm8** [comment]
磁盘太小了，产电大一些根本就不够用，随便一个聚变堆就塞满了，更别说一些更bt的mod了
