### ISSUE TITLE
Applied Flux: Accessor can't output to interfaces.

### ISSUE THREAD

**Issue by Kevin-Marsh** [GlodBlock/ExtendedAE#64]
I am playing around with the accessor while trying to power subnets. It appears that having an accessor against an interface won't push power into the subnet storage buses. Having an external energy source pushing into the interface however works perfectly. If possible could you make it that this setup works? It provides an effective and compact method for combining power into subnets.

Edit: Alternatively it could work if an accessor could push into an accessor so that that could be used as a bridge instead of accessor - interface.

![2024-01-30_16 37 54](https://github.com/GlodBlock/ExtendedAE/assets/9076964/1768378d-44be-4249-aef6-f21d784a5d9b)

![2024-01-30_16 47 38](https://github.com/GlodBlock/ExtendedAE/assets/9076964/a08df599-965c-4b05-a44a-f9bfd9e39ede)

**Comment by GlodBlock** [comment]
fixed in 1.1.0 https://legacy.curseforge.com/minecraft/mc-mods/applied-flux/files/5068921
