### ISSUE TITLE
应用能量的一个小小bug。

### ISSUE THREAD

**Issue by tangzixiang-hash** [GlodBlock/ExtendedAE#69]
前几天我看到你上了新的mod，应用能量，用起来感觉很好。
一开始我使用接口加通用线缆主动抽出然后给powan的下界线缆供电，然后下界线缆不能直接连到接口上，因为线缆不具备主动抽取能力，然后我就加了MEK的。
今天我回头想了想，不是有个主动功能的吗，然后我就用了这个，发现一个bug
![image](https://github.com/GlodBlock/ExtendedAE/assets/60438085/49eb1734-83b0-4163-a162-e8f917178895)
powah的线缆lianjieshang连接上时，不会主动有连接的效果，我以为没法连接的，其实是有有效果，可以供电的，但是视觉显示没有连接上。
我的供电方式是用Flux的无线供电给接口，然后输入到ME驱动器，丢个一个元件，然后用接口再输出，这样没问题把。
![image](https://github.com/GlodBlock/ExtendedAE/assets/60438085/ef5083c2-d36b-4081-b366-ade8d58e5106)

**Comment by GlodBlock** [comment]
修了
