### ISSUE TITLE
ME Packing Tape not packaging all blocks

### ISSUE THREAD

**Issue by CobaltSparkz** [GlodBlock/ExtendedAE#71]
Version: 1.20-1.0.3-forge, as per current ATM9 version

Issue: ME Packing Tape is not able to package extended pattern providers if in "Flat" mode, rather than cube mode. 

Guide states that "device list is configurable" - No config to be found or option where said list can be configured

**Comment by GlodBlock** [comment]
fixed in 1.0.7 https://legacy.curseforge.com/minecraft/mc-mods/ex-pattern-provider/files/5089358
the config file is `expatternprovider-common.toml`
