### ISSUE TITLE
Tag Export Bus doesn't respect filtering/syntax correctly.

### ISSUE THREAD

**Issue by CanvasofSpores** [GlodBlock/ExtendedAE#72]
After some testing, it seems that the tag export bus isn't respecting syntax correctly for certain operators. For example, using the same syntax as one of the filters put into the guidebook page for the storage bus, `forge:dyes/* && !(forge:dyes/black)` the bus isn't pulling anything from my network into other storages. I also tried this by specifying other items, and it didn't seem to work either. Using just a single tag does seem to work fine, it also seems to work fine when specifying multiple items via the OR tag `|`

**Comment by CanvasofSpores** [comment]
All this being said, I'm not sure if it's user error, but following the information in the guide book is all I really have to go off of for the syntax.

**Comment by GlodBlock** [comment]
the logic operator `!` isn't functional now and will be removed next update. the example in guide book will get revised

**Comment by GlodBlock** [comment]
fixed in https://legacy.curseforge.com/minecraft/mc-mods/ex-pattern-provider/files/5092194
