### ISSUE TITLE
[1.20.1] Can't join server with latest version

### ISSUE THREAD

**Issue by FrozenGalaxy** [GlodBlock/ExtendedAE#76]
When joining the server I disconnect with this error:
```
[14Feb2024 00:05:22.972] [Netty Client IO #5/WARN] [com.connectivity.Connectivity/]: Packet data:
{
  "f_132075_": "translation{key='disconnect.genericReason', args=[Internal Exception: java.lang.NullPointerException: Cannot invoke \"net.minecraft.nbt.CompoundTag.m_128459_(String)\" because \"nbt\" is null]}"
}
```

Sadly no other crash logs

**Comment by GlodBlock** [comment]
please provide me with the `latest.log` in logs file
i can't reproduce this issue at server side

**Comment by FrozenGalaxy** [comment]
Here is the full (giant) log:
https://gist.github.com/FrozenGalaxy/d42c9c54236ee7205ee077727c00f986

Look for `[15Feb2024 01:23:40.259] [Netty Client IO #1/WARN] [com.connectivity.Connectivity/]: Packet data:`

I'm not even sure that your mod is the issue anymore.. this error is so vague I have no idea how to debug it

**Comment by GlodBlock** [comment]
does remove extendedae fix this? i doubt it is certain rei plugin break it

**Comment by FrozenGalaxy** [comment]
> does remove extendedae fix this? i doubt it is certain rei plugin break it

I think I found the issue in AvaritiaLite
