### ISSUE TITLE
Port infinity water/cobblestone cell to 1.12.2

### ISSUE THREAD

**Issue by ghost** [GlodBlock/ExtendedAE#8]
Infinite water has been a problem in all versions🙏🙏🙏

**Comment by ZeroNinel** [comment]
enable sink（Cooking for Blockheads）
thanks :D

**Comment by GlodBlock** [comment]
soon maybe

**Comment by GlodBlock** [comment]
added https://github.com/GlodBlock/ExtendedAE/releases/tag/1.12-0.0.1
