### ISSUE TITLE
弄个自动缓存物品的，不是缓存原料的

### ISSUE THREAD

**Issue by gjmhmm8** [GlodBlock/ExtendedAE#82]
https://github.com/GlodBlock/ExtendedAE/issues/81

**Comment by GlodBlock** [comment]
那是什么

**Comment by gjmhmm8** [comment]
就是自动维持网络内物品在一定数量，不够就自动合成

**Comment by GlodBlock** [comment]
https://www.curseforge.com/minecraft/mc-mods/merequester 用这个

**Comment by gjmhmm8** [comment]
对了，复制锻造模板那玩意好不好兼容，最好把ae不能复制物品这事搞一下，不然很麻烦

**Comment by GlodBlock** [comment]
复制物品是什么，详细一点

**Comment by gjmhmm8** [comment]
<img width="256" alt="Snipaste_2024-02-17_13-36-54" src="https://github.com/GlodBlock/ExtendedAE/assets/73775469/f651b9f0-4933-438b-9185-4fa57edf149f">
类似这种

**Comment by gjmhmm8** [comment]
<img width="310" alt="Snipaste_2024-02-17_13-37-20" src="https://github.com/GlodBlock/ExtendedAE/assets/73775469/3c51f1d1-a07f-4bc5-8354-05d5c3c3f550">
还有这种

**Comment by gjmhmm8** [comment]
rs目前是勉强可合，ae是完全合不了

**Comment by GlodBlock** [comment]
这个不能，ae没法实现包含输出产品的输入

**Comment by gjmhmm8** [comment]
那能不能改样板实现，把那种编码成出来输出产品以外的东西合成输出减输入，再缓存一份输入在样板里面

**Comment by GlodBlock** [comment]
不确定能不能，我过几天来试一下

**Comment by gjmhmm8** [comment]
可以的话最好把灌装也给弄一下，类似于拿桶或者储罐在里面左键或者右键那种

**Comment by gjmhmm8** [comment]
包括魔力，源质等等，有些mod包搞这玩意麻烦的要死

**Comment by GlodBlock** [comment]
不太懂，灌装直接拿容器在终端里灌装不就好了

**Comment by gjmhmm8** [comment]
自动化灌装

**Comment by gjmhmm8** [comment]
就比如说1个熔岩桶合成1b熔岩

**Comment by gjmhmm8** [comment]
或者说自动合成满魔力的魔力石板等等

**Comment by gjmhmm8** [comment]
复制那玩意感觉可以参考一下封包合成，用一个包合成一个包加上要复制的东西

**Comment by GlodBlock** [comment]
> 就比如说1个熔岩桶合成1b熔岩

就是说可以用含流体的容器合成对应流体吗，这个应该可以做。但是你只要用个可以交互物品的储罐就可以实现了，额外做个专门的机器我感觉没必要

> 复制那玩意感觉可以参考一下封包合成，用一个包合成一个包加上要复制的东西

封包合成也不能实现复制功能，这个东西我想了两天感觉还是没法做，因为涉及到ae对物品计算的逻辑，ae不能实现任何带循环的合成配方（A做B，B做A这种的）

**Comment by GlodBlock** [comment]
你说的是不是这个东西
https://www.mcmod.cn/item/65121.html

**Comment by gjmhmm8** [comment]
差不多，但不完全是桶，最好就是用样板标记，比如说多少mb的流体加个什么储罐合成一些东西

**Comment by gjmhmm8** [comment]
差不多，但不完全是桶，最好就是用样板标记，比如说多少mb的流体加个什么储罐合成一些东西，还有就是一些魔力石板，源质罐，甚至fe之类的

**Comment by gjmhmm8** [comment]
最好学锻造台和切石机直接用分子装配室，实在不行搞个类似的灌装机也不是不行
