### ISSUE TITLE
无限圆石元件和无限水元件不能存入圆石和水

### ISSUE THREAD

**Issue by gjmhmm8** [GlodBlock/ExtendedAE#83]
无限圆石元件和无限水元件不能存入圆石和水，很容易占用过大，建议改为无限存入

**Comment by GlodBlock** [comment]
给无限元件插溢出卡
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/d7b60b6b-8224-41bc-bdad-df494626101b)
