### ISSUE TITLE
Is extendedae causing me performance issues?

### ISSUE THREAD

**Issue by funnycubeguy** [GlodBlock/ExtendedAE#86]
My ae2 is using up to 30% of thread with only 5 players online. Is extendedae the cause?

![image](https://github.com/GlodBlock/ExtendedAE/assets/9994438/18ee7061-0128-4906-a523-043612b9e036)

**Comment by GlodBlock** [comment]
how many me tag export bus do you have in ae system?

**Comment by funnycubeguy** [comment]
Not many export buses I checked with everyone on the server. maybe like 50 total

**Comment by GlodBlock** [comment]
ok, i see. i will optimize it in next update, but extended ae stuff only takes 1.27% in your profile so it isn't the main issue here

**Comment by funnycubeguy** [comment]
not sure if this is much help but I replaced all extended ae items with regular ae items and the lag is gone. we went from around 15tps to 20tps which is good now no issue

**Comment by GlodBlock** [comment]
all extendedae stuff or only the export bus?

**Comment by funnycubeguy** [comment]
all extendedae for some reason the drives had a big impact but i dont see them on the profiler

**Comment by GlodBlock** [comment]
do you have the full profile link?

**Comment by funnycubeguy** [comment]
https://spark.lucko.me/jaAWTKxhMn this is the profile link for that screen shot

**Comment by GlodBlock** [comment]
extended drives reuse the ae's code so it shares ae's id in the profile. currently i have no idea about why it is laggy.

**Comment by GlodBlock** [comment]
![image](https://github.com/GlodBlock/ExtendedAE/assets/60341015/e2786a05-88a9-4053-9085-7d94585418a8)
it is probably related to other mods

**Comment by GlodBlock** [comment]
the export bus lag is fixed in latest https://legacy.curseforge.com/minecraft/mc-mods/ex-pattern-provider/files/5130025
