### ISSUE TITLE
[request] Wireless Extended Pattern Access Terminal

### ISSUE THREAD

**Issue by mazunki** [GlodBlock/ExtendedAE#89]
We have a ME Extended Pattern Access Terminal. Could we get an Wireless Extended Pattern Access Terminal too?

Hopefully, if we do get this, it would work fine with AE2WTLib's universal terminal.

Thanks for a great mod :)

**Comment by GlodBlock** [comment]
added now.
AE2WTLib's stuff can't be done at my side, please connect the author
