### ISSUE TITLE
灌装机bug

### ISSUE THREAD

**Issue by gjmhmm8** [GlodBlock/ExtendedAE#90]
1、添加反向灌装模式（如流体桶反向灌装成流体和空桶）
2、优化灌装机实现（灌装为左键点击直到无效，反向灌装为右键点击直到无效）（目前还有部分兼容ae2的mod无法灌装）

**Comment by GlodBlock** [comment]
2能不能讲的详细一点，不是很懂你的意思

**Comment by gjmhmm8** [comment]
调用ae自身的灌装方法，而不是疯狂写if

**Comment by gjmhmm8** [comment]
不然每新出一个mod就得去兼容

**Comment by gjmhmm8** [comment]
<img width="628" alt="Snipaste_2024-03-03_20-47-33" src="https://github.com/GlodBlock/ExtendedAE/assets/73775469/0766aadd-ace8-46c5-b8d9-16ef89c72c2f">

**Comment by asdflj** [comment]
什么,有灌注机了?我怎么没看到

**Comment by gjmhmm8** [comment]
> 什么,有灌注机了?我怎么没看到

最新版本，但是还不能反向灌装，兼容性还有点问题

**Comment by asdflj** [comment]
![1da83000cd966abfd2f4b3ab50fcaac9](https://github.com/GlodBlock/ExtendedAE/assets/33802162/11830e19-210d-4ff1-ba08-02cfc9500505)
