### ISSUE TITLE
这个啥情况

### ISSUE THREAD

**Issue by gjmhmm8** [GlodBlock/ExtendedAE#93]
开发mod后runclieent加载阶段crash然后报错（其他mod没问题，ae2系列的才有）
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class appeng.block.misc.MysteriousCubeBlock tried to access private method 'boolean net.minecraft.world.level.block.Blocks.never(net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos)' (appeng.block.misc.MysteriousCubeBlock is in module ae2@15.0.21 of loader 'TRANSFORMER' @663f237a; net.minecraft.world.level.block.Blocks is in module minecraft@1.20.1 of loader 'TRANSFORMER' @663f237a)

**Comment by gjmhmm8** [comment]
神奇，加mek就蹦，不加就不蹦

**Comment by GlodBlock** [comment]
这是哪里的崩溃，你在搭开发环境吗

**Comment by gjmhmm8** [comment]
嗯

**Comment by GlodBlock** [comment]
你是直接用的我的bulid.gradle吗，如果不是给我看一下你的。你这里是ae的at没正常加载导致的

**Comment by gjmhmm8** [comment]
dependencies {
    minecraft "net.neoforged:forge:${minecraft_version}-${forge_version}"
    implementation fg.deobf("curse.maven:glodium-957920:5024300")
    implementation fg.deobf("curse.maven:applied-energistics-2-223794:4777696")
    compileOnly fg.deobf("mezz.jei:jei-1.20.1-forge:15.0.0.12")
    // for some reason this deobf jar fails to load at file correctly
    compileOnly fg.deobf("curse.maven:jade-324717:4768593")
    compileOnly fg.deobf("curse.maven:gregtechceu-modern-890405:5041060")
    annotationProcessor 'org.spongepowered:mixin:0.8.4:processor'
    // runtime test
    runtimeOnly fg.deobf("mezz.jei:jei-1.20.1-forge:15.0.0.12")
    runtimeOnly fg.deobf("curse.maven:jade-324717:4768593")
    runtimeOnly fg.deobf("curse.maven:ender-io-64578:4920828")
    runtimeOnly fg.deobf("mekanism:Mekanism:${mekanism_version}")// Mekanism 加上就报错，删了就没事

}
[build.zip](https://github.com/GlodBlock/ExtendedAE/files/14517757/build.zip)

**Comment by gjmhmm8** [comment]
灌装机那个啥时候搞一下

**Comment by GlodBlock** [comment]
灌装机已经写完了，还没发布。
mek的那个崩溃我也不清楚，你看看appmek的gradle怎么写的

**Comment by gjmhmm8** [comment]
对了，appflux那个转换点上限能不能改long或者bigint

**Comment by GlodBlock** [comment]
不能，forge的api就是用的int

**Comment by gjmhmm8** [comment]
那mek那玩意是怎么绕上限的

**Comment by gjmhmm8** [comment]
创造能量立方那玩意绝对超int上限了

**Comment by gjmhmm8** [comment]
还是说它自己又实现了一套

**Comment by gjmhmm8** [comment]
之前那个ae植物魔法forge也是一样，frabic就没事

**Comment by GlodBlock** [comment]
> 创造能量立方那玩意绝对超int上限了

mek用的他们自己的能量api（焦耳），和fe转化的时候还是最大int

**Comment by gjmhmm8** [comment]
那就不清楚了，flux network还是可以传超过int的

**Comment by gjmhmm8** [comment]
循环估计可以，但应该挺卡的

**Comment by gjmhmm8** [comment]
还有就是me接口那里最好改LONG MAX

**Comment by gjmhmm8** [comment]
无限圆石和无限水好像也是可以改long的

**Comment by GlodBlock** [comment]
不改，那样话你们就会用接口来存电了

**Comment by gjmhmm8** [comment]
最起码改上G

**Comment by gjmhmm8** [comment]
或者说上限为ae网络最大值和LONG max去最小值

**Comment by gjmhmm8** [comment]
然后那个传输的最好也是这么改

**Comment by gjmhmm8** [comment]
现在mek随便一个终极疏导都上T了，上限上来弄大容量还有些用

**Comment by GlodBlock** [comment]
ae里存量上限就是long，扩容是肯定不会也没必要的

**Comment by gjmhmm8** [comment]
LONG基本上就够了

**Comment by gjmhmm8** [comment]
现在gregtech一个终极电池就要4个LONG，一个满级龙球就要一个LONG，而且ae系列还不吃加速火把

**Comment by gjmhmm8** [comment]
说实在的，ae存量上限是long，但通过存储元件应该还可以继续突破，只是不会显示

**Comment by asdflj** [comment]
不能哦,这样就溢出了

**Comment by gjmhmm8** [comment]
显示long，实际上用bigint存

**Comment by gjmhmm8** [comment]
咋可能溢出

**Comment by gjmhmm8** [comment]
虽说我也不知道ae是怎么对达到long上限的东西进行处理的，直接销毁还是无法存入，还是说不处理等溢出

**Comment by gjmhmm8** [comment]
@asdflj

**Comment by asdflj** [comment]
看我的头像

**Comment by asdflj** [comment]
萌新,不懂

**Comment by gjmhmm8** [comment]
不会没写过mod吧

**Comment by gjmhmm8** [comment]
ae2那玩意存储上限也不知道是long还是bigint

**Comment by gjmhmm8** [comment]
> 不能哦,这样就溢出了


https://github.com/GlodBlock/ExtendedAE/assets/73775469/4ce1db92-78b7-415f-9be1-973731e726cc

真*无限存储磁盘

**Comment by gjmhmm8** [comment]
@asdflj
