### ISSUE TITLE
Buffer energy storage

### ISSUE THREAD

**Issue by ArthwrWilly** [GlodBlock/ExtendedAE#97]
I think that the buffer is not supposed to be that big of a battery.
I'm not sure of the actual limit, it takes quite a long time to transfer those amounts at the 32bit limit, but I would guess that the limit is the 64bit limit.
![2024-03-13_19 43 48](https://github.com/GlodBlock/ExtendedAE/assets/30034331/1edd2f12-b9ab-4d87-ad27-1cdea1dd7bf0)

**Comment by GlodBlock** [comment]
i forgo 💀 
it is fixed and should be 10k FE per slot now
